project:
  type: website
  output-dir: docs

website:
  title: "talks"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: default
    css: styles.css
    toc: true
    output-ext: html
  revealjs:
    output-ext: htm



editor: visual

