---
title: "Acts242"
editor: visual
---

Devotion

Committment that flows out of the heart

Obstinately persistent

What is it in your life that you're committed

Early church - product of committment

If we want the effectiveness of the early church, we need the devotion of the early church

Ineffectiveness of church

-   Distraction of the current church- phones
-   Short attention spans. Average attention spans 8sec - less than a goldfish

1 - Devotion to Word of God

Church had just experienced Pentacost. Temptation for early church to want more experience (eg tongues of fire). Instead, they are devoted to scripture.

Jesus taught them from the (Hebrew) scriptures during the 40 days after resurrection. Their hearts burned within them. "They saw the fact of Christ in the pages of scripture"

-   Moses as type of Jesus
-   Joseph - Evil done to me by wicked men was so that many could be saved.

Early church did not see a dichotomy between God's word and the experience of the power of the Spirit

> You need to read!

2\) Devoted to community

Koinonea - word used only once in New Testament (when used outside New Testament, was used

Terms used to refer to early church members:

-   Adelphoi - 350 times = brothers and sisters

-   Disciples - 600 times

\*\*All\* were together (no isolated Christians)
