---
title: "Sarcopenia in Colorectal Cancer"
editor: visual
bibliography: zotero.bib
---

# Colorectal Cancer

## Surgical Patients

2100 patients with LOS for 1139.predictors of LOS: age, surgical approach, major complications (incidence rate ratio \[IRR\] 2.42; 95% confidence interval \[CI\] 2.18--2.68), study cohort, and three body composition profiles characterized by myosteatosis combined with either sarcopenia (IRR, 1.27; 95% CI 1.12--1.43) or VO (IRR, 1.25; 95% CI 1.10--1.42), and myosteatosis combined with both sarcopenia and VO (IRR, 1.58; 95% CI 1.29--1.93). risk of readmission was associated with VO alone (odds ratio \[OR\] 2.66; 95% CI 1.18--6.00); P = 0.018), VO combined with myosteatosis (OR, 2.72; 95% CI 1.36--5.46; P = 0.005), or VO combined with myosteatosis and sarcopenia (OR, 2.98; 95% CI 1.06--5.46; P = 0.038). Importantly, the effect of body composition profiles on LOS and readmission was independent of major complications" [@martin2669]

Sarcopenia is associated with postoperative infection and delayed recovery from colorectal cancer resection surgery. Br J Cancer. 2012;107(6):931--6[@lieffers931]

142 colectomy patients, of whom 17 had sarcopenia showed sarcopenia predicted complications after colectomy[@huangO256]. However, addition of grip strength and low gait speed added to ability to predict postoperative complications.

Psoas muscle area associated with postop complications after colectomy [@jonesO20]

124 laparoscopic colectomies. No difference in LOS, complications, or functional recovery (time to first flatus, oral diet tolerance and mobilization) depending upon sarcopenia.[@pedziwiatr779]

60 patients who underwent laparoscopic colorectal resection for primary colorectal cancer sarcopenia group (normalized total psoas muscle area in males, \<538 mm/m(2); in females, \<346 mm/m(2); n = 20) and nonsarcopenia group (n = 40). No significant differences in the overall rate of postoperative complications (20% vs. 20%) or major postoperative complications of Clavien-Dindo Grade III or more (5% vs. 5%) were observed [@ouchi366]

Muscle radiodensity and mortality in patients with colorectal cancer Kroenke 3008 pmid 29797673

## Colectomy for colorectal cancer

Impact of sarcopenia on surgical and oncologic outcomes of laparoscopic surgery for colorectal cancer. Sarcopenia associated with readmission after colectomy for colorectal cancer 209 patients who underwent laparoscopic surgery for colorectal cancer. sarcopenia was 41.1%. Sarcopenic patients experienced shorter operative times and a lower incidence of surgical site infections; however, the incidence of severe postoperative complications and readmission were increased for this group. Although the 3-year disease-free survival rate was not statistically different between groups, sarcopenic patients had a significantly worse 3-year overall survival rate compared with than the non-sarcopenic group.[@takenami2686]

## Colorectal Cancer

Data from Kaiser [@xiao615] examined 3263 patients with non-metastatic colorectal cancer. Black patients had higher lower rates of sarcopenia according to the definition of Prado et al. Patients with higher neutrophil-lymphocyte ratio had higher risk of muscle abnormality. CT scan at L3 was analyed to determine SMI,IMAT,VAT,SAT and TAT (=VAT+SAT+IMAT) using SliceOMatic. Threshold values determined for optimal stratification (cf [@martin1539] [@prado639]

Kaiser 3262 patients with stage I-III colorectal cancer of whom 42% were sarcopenic. [@caan1008] examined body composition and survival from colorecal cncer at Kaiser. Worst survival with low muscle mass and high adiposity. Slightly worse survival with elevated VAT but no worse survival with increases SAT. Different relationships between TAT and survival by sex.

> The existence of nonlinear relationships between sarcopenia and body composition measures and overall mortality were assessed by the addition of restricted cubic splines and use of the likelihood ratio test that compared models with the linear terms only with those with both linear and cubic spline terms. Effect modification was assessed using cross-product terms for body composition measures and the following covariates: sex, age at diagnosis (\<60, 60--\<70, and 70 years), BMI category (18.5\<25, 25--\<30, and 30 kg/m2), weight change prior to diagnosis (stable, 5% loss, 5% gain), cancer stage (I, II/III), tumor site (rectal vs. colon), and chemotherapy (any vs. none).

Trejo-Avila M, Bozada-Gutiérrez K, Valenzuela-Salazar C, Herrera-Esquivel J, Moreno-Portillo M. Sarcopenia predicts worse postoperative outcomes and decreased survival rates in patients with colorectal cancer: a systematic review and meta-analysis. Int J Colorectal Dis. 2021;36(6):1077--96. doi: 10.1007/s00384-021-03839-4

.Preoperative Assessment of Cancer in the Elderly (PACE): Audisio RA, Pope D, Ramesh HS, Gennari R, van Leeuwen BL, West C, et al. Shall we operate? Preoperative assessment in elderly cancer patients (PACE) can help. A SIOG surgical task force prospective study. Crit Rev Oncol Hematol. 2008;65:156--63

Heriot AG, Tekkis PP, Smith JJ, Cohen CR, Montgomery A, Audisio RA, et al. Prediction of postoperative mortality in elderly patients with colorectal cancer. Dis Colon Rectum. 2006;49:816--24

Pope D, Ramesh H, Gennari R, Corsini G, Maffezzini M, Hoekstra HJ, et al. Pre-operative assessment of cancer in the elderly (PACE): a comprehensive assessment of underlying characteristics of elderly cancer patients prior to elective surgery. Surg Oncol. 2006;15:189--97

### Sarcopenia and advanced CRC

French investigators studied 51 patients with mCRC and found sarcopenia in 70% (39% of women and 82% of men). In multivariate analysis including age, sex, BMI, sarcopenia, SAT, and VAT, the only factor associated with Grade 3-4 toxicities was sarcopenia (odds ratio = 13.55; 95% confidence interval \[1.08; 169.31\], P = 0.043).[@barrett583]

Data from Kaiser [@xiao615] examined 3263 patients with non-metastatic colorectal cancer. Black patients had higher lower rates of sarcopenia according to the definition of Prado et al. Patients with higher neutrophil-lymphocyte ratio had higher risk of muscle abnormality. CT scan at L3 was analyed to determine SMI,IMAT,VAT,SAT and TAT (=VAT+SAT+IMAT) using SliceOMatic. Threshold values determined for optimal stratification (cf [@martin1539; @prado639]

Low muscle mass has been shown to be associated with poor prognosis cancer patients.[@martin1539] This may be due to overal frailty or low muscle mass may lead to increased toxicity from chemotherapy due to pharmacokinetic mechanism. 5-FU is hydrophilic and it volume of distribution includes the muscle compartment, while oxaliplatin is hydrophobic, with distribution in the fat compartment[@bozzetti2107].

In addition, loss of muscle mass during chemotherapy for advanced cancers is a poor prognosticator.

Blauhoff [@blauwhoff-buskermolen1339] studis 67 patients with metastatic colorectal cancer. Muscle area on CT decreased by 6.1% over 3 months. Patients in the lowest tertile (loss of 9%) had worse survial. Overall survival 17.5 months for first-line chemotherapy and 8.5months for second-line. Baseline muscle density was predictive of survival on multivariable analysis, but low SMI at baseline was not associatesd with survival. (This may be because sarcopenic obesity is the major risk factor, and there were few obese patients in the study cohort) \>Muscle loss of 9% or more remained independently associated with survival when adjusted for sex, age, baseline lactate dehydrogenase concentration, comorbidity, mono-organ or multiorgan metastases, treatment line, and tumor progression at first evaluation by computed tomography scan (hazard ratio, 4.47; 95% CI, 2.21 to 9.05; P , .001). We found a mean coefficient of variation between observers of 0.6% for skeletal muscle area in a random sample of 20 patients, which is regarded to be low.[@macdonald342]. Changes between the first and second scans were calculated as a rate of change per 3 months, meaning change per first evaluation, to compare with available literature.\[awad74\]\[prado1583\]Relative muscle change per 3 months was categorized into tertiles of muscle change: tertile one, highest muscle loss up to 9%; tertile two, muscle loss of 9% to 1.5%; and tertile three, muscle loss of 1.5% until highest gain in muscle. However, the survival curve of tertile two was not significantly different from the survival curve of tertile three (log-rank P = .961); therefore tertiles two and three were pooled (cutoff, 9% muscle loss).

Kurk [@kurk1033] found that skeletal muscle loss during chemotherapy was associated with decreased progression-free and overall- survival in metastatic colorectal cancer.

> Detailed changes in skeletal muscle mass and body weight during CAIRO3 treatments were previously reported.KurkS, p909, 2018) We additionally analyzed changes in SMI and BMI during these treatments by linear mixed effects models.(Bayar MA,p311,2017) The baseline value of the outcome (SMI/BMI) was included in the outcome vector. Potential confounders were age, sex, lactate dehydrogenase (LDH) levels, best response to initial six cycles CAPOX‐B, resection of the primary tumor, and the number of metastatic sites. The final model was selected based on the Akaike Information Criterion (AIC) and included: treatment arm, time, age, sex, resection primary tumor, and the interaction of treatment arm by time as fixed effects. Modeling time as a random effect did not increase the model fit as indicated by the AIC. To investigate differences in SMI and BMI changes over time between the CAIRO3 treatment arms, we checked the significance of the two‐way interaction including treatment arm by time.

> During p2 (maintenance CAP‐B/observation), again absolute SMI and BMI at the start (t1) of treatment were not associated with early progression and death. In contrast, SMI loss and BMI loss during treatment were associated with early progression and death.

Fogelman [@fogelman307] treated patients undergoing chemotherapy with a novel agent designed to reduce muscle less. CT scans at 2 months were compared with baseline scans prior to chemotherapy.

> Changes in skeletal muscle were determined using routinely acquired CT scans for patients on the study. We calculated skeletal muscle cross-sectional area (cm2) at the third lumbar vertebra (L3). A single slice at the mid-point of L3 was used, preferably a 2.5-mm slice if available, and a 5-mm slice if a 2.5-mm slice was not available. The L3 is a landmark that has been extensively used and validated in studies assessing body composition in cancer patients [@shen2333][@prado269] . Skeletal muscle surface areas were determined using Slice-o-Matic softwareTM, version 4.3 (Tomovision, Montreal, QC, Canada) using pre-established thresholds of Hounsfield units (HU) of −29 to +150 [@mitsiopoulos115]. We additionally evaluated adipose tissue cross-sectional area (subcutaneous, visceral, and intramuscular) in the L3 region as described previously [@mourtzakis997]. Changes in muscle and adipose tissue surface areas over time were determined for each patient from the baseline study to the first CT post treatment, done after 2 months. We looked at muscle loss as a continuous variable and defined "meaningful loss" as greater than a 6 cm2 difference from the baseline to the second scan. We chose this cut point as it is equivalent to 1 kg of skeletal muscle and is associated with physical function (i.e., muscle strength). Additionally, this cut point has been used to investigate significant changes in muscle mass throughout cancer disease trajectory [@shen2333][@frontera1038][@prado1012].

Prado [@prado1012] looked at changes in 1279 CT scans in 368 patients with advanced cancer. The last available interval with CT scans was chosen for comparison. Categorized into stable, gaining, losing for muscle and for adipose tissue. Adipose tissue was ?? sum of visceral adipose tissue and subcutaneous tissue. (**Did not use SMI**). Muscel loss and adipose loss seemed correlated, with larger magnitude of adipose tissue loss at short interval to death. (Authors conclusion that muscle and adipose tissue loss in the past 3 months of life is likely not possible) \>Advanced-cancer patients (n = 368; median survival: 196 d) had a total of 1279 CT images over the course of their disease. With consideration of all time points, muscle loss occurred in 39% of intervals between any 2 scans. However, the overall frequency of muscle gain was 15.4%, and muscle was stable in 45.6% of intervals between any 2 scans, which made the maintenance or gain of muscle the predominant behavior. Multinomial logistic regression revealed that being within 90 d (compared with \>90 d) from death was the principal risk factor for muscle loss (OR: 2.67; 95% CI: 1.45, 4.94; P = 0.002), and muscle gain was correspondingly less likely (OR: 0.37; 95% CI: 0.20, 0.69; P = 0.002) at this time. Sex, age, BMI, and tumor group were not significant predictors of muscle loss or gain. A much higher proportion of men (61%) than women (31%) met the criteria for sarcopenia. Changes in muscle and adipose tissue over time were calculated as the absolute loss or gain of tissue area during each scan interval. The precision error of measurements was \~1.5% [@mourtzakis997] with a minimum detectable change of \~3 cm2. We attributed the change during each interval into the following categories: 1) muscle loss ≥6.0 cm2, 2) stable muscle ±5.9 cm2, or 3) muscle gain ≥6.0cm2. These cutoffs are equivalent to a loss or gain of ≥1 kg of skeletal muscle on a whole-body basis and are associated with alterations in muscle strength [@shen2333][@frontera1038]. For adipose tissue, categories were based on the equivalence of 14.7 cm2 total fat at L3 and 1 kg tissue on a whole-body basis [@shen2333]; therefore, changes during each interval were categorized as 1) adipose tissue loss ≥14.7 cm2, 2) stable adipose tissue ±14.6 cm2, or 3) adipose tissue gain ≥14.7 cm2. CT scans were taken for the diagnosis, confirmation of stage, and follow-up of disease progression and treatment. With the understanding that cachexia evolves markedly in the end of life and to take advantage of repeated measures, we focused on patients with ≥2 CT images (2--6 images) on record during the year preceding their deaths (n = 368). A selection bias was not apparent in this sample; we showed that the sex distribution, age at death, survival time, primary tumor site, tumor morphology, and body-composition features (ie, muscle and adipose tissues) in patients who had only a single scan were not different from those of the overall cohort at an equal time to death (P \> 0.1). Patients included in the analysis (n = 368) were of advanced stage, and the median time to death of all groups was \<1 y.

Lieffers and advanced colorectal cancer: Found liver and spleen increased in size in terminal patients (causing increase in basal metabolic rate). Found more rapid muscle loss with progressive disease [@lieffers1173]. Different thresholds for VAT (-150 to -50) and SAT(-190 to -30). Also estimated muscel surface area using measurements 5cm above L4[@shen2333]. Most rapid change in body composition between 4 months and 1 month prior to death. \>14% of patients gained skeletal muscle during the year preceding death from colorectal cancer (+4.7 ± 5.4%/100 d).

## Sarcopenia and inflammatory bowel disease

### Inflammation in Colorectal Cancer

[@felicianoe172319] PMID 28796857PMID 24122750PMID 24866483
