---
title: "Disparities Literature"
editor: visual
bibliography: zotero.bib
---

## Literature

### Body composition and Racial/Ethnic differences

Investigators at the University of Illinois {@jang557} examined the change in skeletal muscle index during cancer treatment among 212 patients. Among 132 non-Hispanic Black patients, muscle loss during therapy was greater than non-Hispanic White and Other (Asian + Hispanic) (Odds Ratio 3.29 p=0.004). The loss was highest in Black rectal cancer patients (11 units of SMI loss cm2/m2) vs White rectal Cancer (8 cm2/m2). Loss among colon cancer patients was higher in Black patients ( 5.5 cm2/m2) than in White patients (2.5 cm2/m2). Prior to treatment, Blacks had higher SMI than White (similar to findings of Xaio 2019)

Data from Kaiser {@xaio615} examined 3263 patients with non-metastatic colorectal cancer. Black patients had higher lower rates of sarcopenia according to the definition of Prado et al. Patients with higher neutrophil-lymphocyte ratio had higher risk of muscle abnormality. CT scan at L3 was analyed to determine SMI,IMAT,VAT,SAT and TAT (=VAT+SAT+IMAT) using SliceOMatic. Threshold values determined for optimal stratification (cf {@martin1539;@prado639})

### Body composition in Colorectal cancer

Muscle radiodendity and mortality in patients with colorectal cancer Kroenke 3008 pmid 29797673

French investigators studied 51 patients with mCRC and found sarcopenia in 70% (39% of women and 82% of men). In multivariate analysis including age, sex, BMI, sarcopenia, SAT, and VAT, the only factor associated with Grade 3-4 toxicities was sarcopenia (odds ratio = 13.55; 95% confidence interval \[1.08; 169.31\], P = 0.043).{@barrett_Nutritionand Cancer v6 2014(4)}

Xaio fou

### Body composition and therapy of advanced GI Cancers

### Inflammation in COlorectal Cancer

{@feliciano e172319} PMID 28796857

PMID 24122750

PMID 24866483

Low muscle mass has been shown to be associated with poor prognosis cancer patients.[@martin1539] This may be due to overal frailty or low muscle mass may lead to increased toxicity from chemotherapy due to pharmacokinetic mechanism. 5-FU is hydrophilic and it volume of distribution includes the muscle compartment, while oxaliplatin is hydrophobic, with distribution in the fat compartment[@bozzetti2107].

In addition, loss of muscle mass during chemotherapy for advanced cancers is a poor prognosticator.

Blauhoff [@blauwhoff-buskermolen1339] studis 67 patients with metastatic colorectal cancer. Muscle area on CT decreased by 6.1% over 3 months. Patients in the lowest tertile (loss of 9%) had worse survial. Overall survival 17.5 months for first-line chemotherapy and 8.5months for second-line. Baseline muscle density was predictive of survival on multivariable analysis, but low SMI at baseline was not associatesd with survival. (This may be because sarcopenic obesity is the major risk factor, and there were few obese patients in the study cohort) \>Muscle loss of 9% or more remained independently associated with survival when adjusted for sex, age, baseline lactate dehydrogenase concentration, comorbidity, mono-organ or multiorgan metastases, treatment line, and tumor progression at first evaluation by computed tomography scan (hazard ratio, 4.47; 95% CI, 2.21 to 9.05; P , .001). We found a mean coefficient of variation between observers of 0.6% for skeletal muscle area in a random sample of 20 patients, which is regarded to be low.[@macdonald342]. Changes between the first and second scans were calculated as a rate of change per 3 months, meaning change per first evaluation, to compare with available literature.\[awad74\]\[prado1583\]Relative muscle change per 3 months was categorized into tertiles of muscle change: tertile one, highest muscle loss up to 9%; tertile two, muscle loss of 9% to 1.5%; and tertile three, muscle loss of 1.5% until highest gain in muscle. However, the survival curve of tertile two was not significantly different from the survival curve of tertile three (log-rank P = .961); therefore tertiles two and three were pooled (cutoff, 9% muscle loss).

Awad [@awad74]studies changes in body composition during neodjuvant chemotherapy for esophagogastric cancer.

Kurk [@kurk1033] found that skeletal muscle loss during chemotherapy was associated with decreased progression-free and overall- survival in metastatic colorectal cancer.

> Detailed changes in skeletal muscle mass and body weight during CAIRO3 treatments were previously reported.KurkS, p909, 2018) We additionally analyzed changes in SMI and BMI during these treatments by linear mixed effects models.(Bayar MA,p311,2017) The baseline value of the outcome (SMI/BMI) was included in the outcome vector. Potential confounders were age, sex, lactate dehydrogenase (LDH) levels, best response to initial six cycles CAPOX‐B, resection of the primary tumor, and the number of metastatic sites. The final model was selected based on the Akaike Information Criterion (AIC) and included: treatment arm, time, age, sex, resection primary tumor, and the interaction of treatment arm by time as fixed effects. Modeling time as a random effect did not increase the model fit as indicated by the AIC. To investigate differences in SMI and BMI changes over time between the CAIRO3 treatment arms, we checked the significance of the two‐way interaction including treatment arm by time.

> During p2 (maintenance CAP‐B/observation), again absolute SMI and BMI at the start (t1) of treatment were not associated with early progression and death. In contrast, SMI loss and BMI loss during treatment were associated with early progression and death.

Fogelman [@fogelman307] treated patients undergoing chemotherapy with a novel agent designed to reduce muscle less. CT scans at 2 months were compared with baseline scans prior to chemotherapy.

> Changes in skeletal muscle were determined using routinely acquired CT scans for patients on the study. We calculated skeletal muscle cross-sectional area (cm2) at the third lumbar vertebra (L3). A single slice at the mid-point of L3 was used, preferably a 2.5-mm slice if available, and a 5-mm slice if a 2.5-mm slice was not available. The L3 is a landmark that has been extensively used and validated in studies assessing body composition in cancer patients [@shen2333][@prado269] . Skeletal muscle surface areas were determined using Slice-o-Matic softwareTM, version 4.3 (Tomovision, Montreal, QC, Canada) using pre-established thresholds of Hounsfield units (HU) of −29 to +150 [@mitsiopoulos115]. We additionally evaluated adipose tissue cross-sectional area (subcutaneous, visceral, and intramuscular) in the L3 region as described previously [@mourtzakis997]. Changes in muscle and adipose tissue surface areas over time were determined for each patient from the baseline study to the first CT post treatment, done after 2 months. We looked at muscle loss as a continuous variable and defined "meaningful loss" as greater than a 6 cm2 difference from the baseline to the second scan. We chose this cut point as it is equivalent to 1 kg of skeletal muscle and is associated with physical function (i.e., muscle strength). Additionally, this cut point has been used to investigate significant changes in muscle mass throughout cancer disease trajectory [@shen2333][@frontera1038][@prado1012].

Prado [@prado1012] looked at changes in 1279 CT scans in 368 patients with advanced cancer. The last available interval with CT scans was chosen for comparison. Categorized into stable, gaining, losing for muscle and for adipose tissue. Adipose tissue was ?? sum of visceral adipose tissue and subcutaneous tissue. (**Did not use SMI**). Muscel loss and adipose loss seemed correlated, with larger magnitude of adipose tissue loss at short interval to death. (Authors conclusion that muscle and adipose tissue loss in the past 3 months of life is likely not possible) \>Advanced-cancer patients (n = 368; median survival: 196 d) had a total of 1279 CT images over the course of their disease. With consideration of all time points, muscle loss occurred in 39% of intervals between any 2 scans. However, the overall frequency of muscle gain was 15.4%, and muscle was stable in 45.6% of intervals between any 2 scans, which made the maintenance or gain of muscle the predominant behavior. Multinomial logistic regression revealed that being within 90 d (compared with \>90 d) from death was the principal risk factor for muscle loss (OR: 2.67; 95% CI: 1.45, 4.94; P = 0.002), and muscle gain was correspondingly less likely (OR: 0.37; 95% CI: 0.20, 0.69; P = 0.002) at this time. Sex, age, BMI, and tumor group were not significant predictors of muscle loss or gain. A much higher proportion of men (61%) than women (31%) met the criteria for sarcopenia. Changes in muscle and adipose tissue over time were calculated as the absolute loss or gain of tissue area during each scan interval. The precision error of measurements was \~1.5% [@mourtzakis997] with a minimum detectable change of \~3 cm2. We attributed the change during each interval into the following categories: 1) muscle loss ≥6.0 cm2, 2) stable muscle ±5.9 cm2, or 3) muscle gain ≥6.0cm2. These cutoffs are equivalent to a loss or gain of ≥1 kg of skeletal muscle on a whole-body basis and are associated with alterations in muscle strength [@shen2333][@frontera1038]. For adipose tissue, categories were based on the equivalence of 14.7 cm2 total fat at L3 and 1 kg tissue on a whole-body basis [@shen2333]; therefore, changes during each interval were categorized as 1) adipose tissue loss ≥14.7 cm2, 2) stable adipose tissue ±14.6 cm2, or 3) adipose tissue gain ≥14.7 cm2. CT scans were taken for the diagnosis, confirmation of stage, and follow-up of disease progression and treatment. With the understanding that cachexia evolves markedly in the end of life and to take advantage of repeated measures, we focused on patients with ≥2 CT images (2--6 images) on record during the year preceding their deaths (n = 368). A selection bias was not apparent in this sample; we showed that the sex distribution, age at death, survival time, primary tumor site, tumor morphology, and body-composition features (ie, muscle and adipose tissues) in patients who had only a single scan were not different from those of the overall cohort at an equal time to death (P \> 0.1). Patients included in the analysis (n = 368) were of advanced stage, and the median time to death of all groups was \<1 y.

Similar study by Tan looking at longitudinal body composition in pancreatic cancer [@tan6973]. 111 patients with metastatic pancreatic cancer: 44 identified with more than one scan. Patients who underwent repeated CT scans were more likely to receive active therapy (71%) and had longer survival than those who had a solitary CT scan (28% receiving active chemotherapy). OVeral median survival 130 days. Age and sarcopenic obesity predicted survival. Sarcopenic obesity had survival of 55 days vs 148 days for those without sarcopenia obesity. Muscle loss was normalized to percent during 100 days. Median interval between scans was ??135 days. Patients grouped in tertiles for muscle gain/loss. Top tertile gained 7% muscle cross-sectional area/100 days, while bottom tertile lost 12% over 100 days. All tertiles lost adipose tissue. **No difference in survival between the tertiles.** \> muscle loss was the prevalent behavior, but 14% of patients with metastatic pancreatic cancer (considered the disease most highly associated with cachexia) exhibited a muscle gain of 7.9 ± 14.4%/100 d).

Lieffers and advanced colorectal cancer: Found liver and spleen increased in size in terminal patients (causing increase in basal metabolic rate). Found more rapid muscle loss with progressive disease [@lieffers1173]. Different thresholds for VAT (-150 to -50) and SAT(-190 to -30). Also estimated muscel surface area using measurements 5cm above L4[@shen2333]. Most rapid change in body composition between 4 months and 1 month prior to death. \>14% of patients gained skeletal muscle during the year preceding death from colorectal cancer (+4.7 ± 5.4%/100 d).

Longitudinal study of patients with advanced non-small cell lung cancer (all with \<1yr survival). [@baracos1133S] \>At referral (median time to death: 265 d), mean body mass index (BMI; in kg/m(2)) was 24.9, with 47.4% of patients being overweight or obese. Only 7.5% overall were underweight as conventionally understood (BMI \< 18.5). Analysis of computed tomography images showed extremely high heterogeneity of muscle mass within all strata of BMI. The overall prevalence of severe muscle depletion (sarcopenia) was 46.8% and was present in patients in all BMI categories.

Caan [@caan1008] examined body composition and survival from colorecal cncer at Kaiser.

### Body composition and gastric cancer

PMID 34774016
