---
title: "Esophageal Cancer Treatment Decisions"
editor: visual
bibliography: zotero.bib
---

# Esophagectomy in the Elderly

Meta-analysis of studies [@baranov131]: 90-day mortality 9% for those 75+ vs 3.9% in those \<75

Groningen: [@faiz986] Esophageal SCCA: Age and co-morbidity wre associated with higher probability of cCRT

Metaanalysis of age and esophageal cancer treatment [@mantziari2104]

Eindhoven cancer registry. Esohpagectomy 90=day mortality 7.1% for \<65 years, 8.7% for 65-74 years, and 15.4% for 75+

# Age and marginal benefit of surgery after ChemoRT

NCDB [@jensendoac050] compared survival with chemoradiation+Surgery vs chemoradiation alone and found a survival benefit to surgery, except for patients over age 80 with adenocarcinoma and patients with squamous cell carcinoma with Charson/Deyo 2 or 3+, in whom there was no survival advantage or detriment to surgery

NCDB [@farrow996] Compared survival of stage II or III esophageal cancer in 17,495 patients, of whom 11,680 underwent esophagectomy and 5815 received chemoradiation. Survival after esophagectomy worsened with increasing age and decreased considerably after age 73. More use of dCRT after age 73. Survival benefit of surgery over chemoradiation in all ages, including octogenarians.

SEER [@lv8483] 1596 Elderly patients with esophageal cancer: 278 had surgery.  Longer survival with trimodality therapy.

The perioperative period is when patients are at most risk of developing cardiopulmonary complications with an operative mortality rate of 13.4% in those who are between 70--79 years old and 19.9% in those over the age of 80 (7,8).

Operative mortality after esophagectomy in those over age 80 is 19.9% (vs 8.8% under age 90) from National Inpatient Sample data [@finlayson729]

# Frailty and complications after esophagectomy

Dublin [@elliott822b] Sarcopenia present in XX % and was associated with increased risk of perioperative complications. Sarcopenia was not associated with hospital mortality, which was 1%. Sarcopenia was associated with reduced 5-year survival, as was loss of muscle mass during neoadjuvant therapy.

Review of sarcopenia and outcomes after GI cancer surgery [@su82] Sarcopenia associated with increased risk of postoperative complications and decreased survival after esophagectomy.

Negative impact of muscle wasting after chemotherapy followed by surgery [@mayanagi3741] 66 pts

Sarcopenia as a predictor of pulmonary complications after esophagectomy for thoracic esophageal cancer [@nishigori678]

# Frailty and survival after esophagectomy

# Retrospective Trimodality vs dCRT

Italy [@castoro1375] Squamous cell 77 patients over 16 years. Comparable survival with dCRT vs Trimodality even after correcting for propensity score

Dutch[@faiz986] Factors accounting for choice of dCRT vs Trimodality: age \>75, hypertension+diabetes, CV+pulmonary. Adenocarcinoma: better survival with Trimodality. SCCA: Age \>75 or \>2 comorbidities overall survival was comparable between groups.

Taiwan [@wang255] 5832 patients with SCC: Trimodality in 1754 and dCRT in 4078. Survival at 3 years 41% with trimodality vs 17% with dCRT

MDACC [@zhou1207] Squamous cell: 143 Trimodality-eligible patients: 60 had trimodality therapy and 83 had chemoRT. Longer survival in trimodality group (77 vs 33 months). For those with a complete clinical response, trimodality resulted in 123 moths survival vs 55 months with dCRT. Trimodality therapy was not associated with longer overall survival but predicted recurrence-free survival.

UK [@hategan612] 102 patients with esophageal cancer: 55 trimodality and 47 dCRT. Longer survival with trimodality

# ChemoRT in Trimodality-eligible patients

MDACC [@taketa300] 662 patient eligible for trimodality therapy received chemoradiation. 61 patients (9.8%) refused surgery.  5-year overall survival 58% and relapse-free survival 35%. 13 patients developed localized recurrences, of whom 12 underwent salvage esophagectomy.

MDCAA [@taketa95]

# Active Surveillance

Dutch preSano [@noordman965]

SANO randomized trial [@noordman142]

Editorial [@vanderwilk462]

# Randomized trials of Trimodality vs dCRT

FFCD 9012 [@bedenne1160] German Trial [@stahl2310]

# Reviews - Trimodality vs dCRT

[@vellayappanCD010511] Addition of surgery to dCRT adds little or benefit for patients with squamous cell carcinoma. Authors could not determine whether there was benefit of the addition of surgery for adenocarcinoma and GE junction cancers.

[@voeten1271] No clear advantage of trimodality therapy over dCRT

# Esophagectomy in the Elderly

Meta-analysis of studies [@baranov131]: 90-day mortality 9% for those 75+ vs 3.9% in those \<75

Groningen: [@faiz986] Esophageal SCCA: Age and co-morbidity wre associated with higher probability of cCRT

Metaanalysis of age and esophageal cancer treatment [@mantziari2104]

# Quality of life after esophagectomy

Esophagectomy is accompanied by profound alterations in quality of life (reviewed in taioli 377).

The EORTC quality of life questionnaire (QLQ-C30) incorporates a 18-question quality of life scale specific for esophageal disease (OES-18) {Aaronson, #1661;Blazeby, #1662;Blazeby,  #1663}.

FACIT {Webster, 2003 #2011}

Cancer FACIT {Cella, 1993 #2015}

# ChemoRT in Trimodality-eligible patients

MDACC [@taketa300] 662 patient eligible for trimodality therapy received chemoradiation. 61 patients (9.8%) refused surgery.  5-year overall survival 58% and relapse-free survival 35%. 13 patients developed localized recurrences, of whom 12 underwent salvage esophagectomy.

MDCAA [@taketa95]

# Active Surveillance

Dutch preSano [@noordman965]

SANO randomized trial [@noordman142]

Editorial [@vanderwilk462]

# Randomized trials of Trimodality vs dCRT

FFCD 9012 [@bedenne1160] German Trial [@stahl2310]

# Reviews - Trimodality vs dCRT

[@vellayappanCD010511] Addition of surgery to dCRT adds little or benefit for patients with squamous cell carcinoma. Authors could not determine whether there was benefit of the addition of surgery for adenocarcinoma and GE junction cancers.

[@voeten1271] No clear advantage of trimodality therapy over dCRT

# Regionalization

Regionalization of complex cancer surgery care. Better outcomes with regionalization of esophagectomy care within a network [@sheetz3234]
