---
title: "Esophagectomy ERAS"
editor: visual
bibliography: zotero.bib
---

# Early Recovery after Esophagectomy

ERAS society guidelines [@low299].

Systmatic review of enhanced recovery for esophagectomy [@findlay413]

## Published experience 

The AME esophagectomy group randomized 118 patients between an early recovery program and standard care. The early recovery group had fewer pulmonary complications (17% vs 33%) and fewer overall complications (33% vs 52%). No difference in anastomotic leakage (12% vs 16%). No difference in length of stay or pain scores[@shen9113].


Meta-analysis [@pisarskae0174382], included 2042 patients (1058 in an ERAS group vs 984 in a traditional group), revealed a significantly shorter hospital stay and fewer non-surgical and pulmonary complications in the ERAS group, but no effect on overall morbidity, mortality or readmission rates.

Meta-analysis of 13 reports of enhanced recovery protocols performed a regression analysis to identify factors which may be important in length of stay reductions.  These factors included immediate extubation, early gastrograffin study, early urinary catheter removal, early feeding with at least sips of water on the first postoperative day, early enteral feeding, and epidural catheter removal within 4 days[@markar1].

Virginia Mason ERAS [@schmidt931]

## Nutritional Assessment

Patients with esophageal cancer frequently suffer from undernutrition due to GI tract obstruction and the pro-inflammatory effects of cancer and the effects of neoadjuvant therapy. Preoperative evaluation should include history of  weight loss, dysphagia, odynophagia. 

Malnutrition Screening Tool is a simple two-question screening tool which can triage patients for more detailed nutritional evaluation.[@skipper709] [@shaw47]

Malnutrition can be graded as mild, moderate, or severe [@white730]

Moderate malnutrition is characterized by weight loss of 5% in 1 month, 7.5% in 3 months, or 10% in 6 months. Severe malnutrition is characterized by weight loss >7.5% in 3 months, and >10% in 6 months, or >20% in 1 year.
 
Nutrition support from has been suggested to improve outcomes after esophagectomy in retrospective studies.[@ligthart-melis587] ESPN (ASPEN?) guidelines suggest strategies for nutritional support in cancer patients.[@arends11]

See Bower and Martin  19373870

Criteria for utility of feeding tubes with esophageal cancer[@huerter948]

J tubes; 
46

Ben-David
K
, Kim
T
, Caban
A M
, Rossidis
G
, Rodriguez
S S
, Hochwald
S N
. Pre-therapy laparoscopic feeding jejunostomy is safe and effective in patients undergoing minimally invasive esophagectomy for cancer
. J Gastrointest Surg
2013
; 17
: 1352
–8
.


1 - No weight loss

2 - 5% weight loss and moderate

3 - 10% weight loss and severe dysphagia

The Global Leadership Initiative on Malnutrition (GLIM) criteria [@jensen32] (see also [@cederholm1])

+--------------------+-----------------------------+----------------------------------+--------------------------+
| Malnutrition Grade | Weight Loss                 | BMI                              | Muslcle Mass             |
+====================+=============================+==================================+==========================+
| Moderate           | 5-10% in past 6 months\     | \<20 if \<70 yr \<22 if \>70yr   | Mild to moderate deficit |
|                    | or 10-20% beyond 6 months   |                                  |                          |
+--------------------+-----------------------------+----------------------------------+--------------------------+
| Severe             | \>10% within past 6 months\ | \<18.5 if \<70yr, \<20 if \>70yr | Severe deficit           |
|                    | or \>20% -beyond 6 months   |                                  |                          |
+--------------------+-----------------------------+----------------------------------+--------------------------+

European consensus on sarcopenia defines sarcopenia based upon grip strength as \<30kg in men and \<20kg in women[@lauretani1851] or uses a categorization based upon BMI: [@friedM146]

| Men - BMI | Grip Strength |     | Women - BMI | Grip Strength |
|-----------|---------------|-----|-------------|---------------|
| \<24      | \<29kg        |     | \<23        | \<17kg        |
| 24-26     | \<30kg        |     | 23-26       | \<17kg        |
| 26-28     | \<30kg        |     | 26-29       | \<18kg        |
| \>28      | \<32kg        |     | \>29        | 21kg          |

Dysphagia score [@knyrim1302] - scale used for esophageal stent paper

**Questions:**

1 - Standardized Nutritional assessment

2 - Standardized Dysphagia score

3 - Categorize weight loss with respect to BMI (Martin, JCO)

4 - Who needs a preoperative feeding tube?

## Preoperative enteral nutrition

Feeding jejunostomy is the traditional approach to enteral tube placement in patients who may undergo surgery in the future. Gastrostomy placement, particularly via the endoscopic approach (PEG) runs the risk of damage to the right gastroepiploic vascular arcade, which might devascularize a future gastric conduit[@ohnmacht311], although small series suggest that this risk is low [@margolis1694].

A meta-analysis of over 1000 patients treated with percutaneous endoscopic gastrostomy prior to esophagectomy found no differences in anastomtic leak rate and no instances of conduit failure due to PEG placement [@fang155]

Anecdotal data suggests that esophagectommy with gastric conduit can safely be performed after gastrostomy, particularly if placement is done via laparoscopy and if the tube can be removed prior to esophagectomy to allow the tract to heal. PEG placement (via endoscopy) runs a small but finite risk of seeding of the gastrostomy tract with tumor.[@ellrichmann526]

\newpage

## Frailty

Frailty [@fried255] Clinical Frailty Score (7-point) predicts death and need for institutional care at 5 years from Canadian Health study [@rockwood489]

Frailty and major surgery [@mcisaac538] [@mosquera272]

## Preoperative functional testing

Cardiopulmonary testing has not been shown to be of proven value in peroperative assement of surgical fitness prior to esophagectomy [@drummond515]

6minute walk test predicts outcome after esophagectomy [@inouedoz050]

review of cardiopulmonary testing: [@older355]

Shuttle walk and cardiopulmonary testing in esophagectomy [@whibley594]

Routine pre- and post-neoadjuvant chemotherapy fitness testing is not indicated for oesophagogastric cancer surgery. [@drummond515]

Does VO2peak Provide a Prognostic Value in Esophagectomy and Gastrectomy for Post-operative Outcomes?[@niels1812]

## Nutritional Repletion

**Question:**

1 - What criteria should be used to guide nutritional repletion in the context of weight loss?

2 - Which patient who don't receive a feeding tube prior to chemoRT need one postop?

## Treatment of anemia

Anemia prior to esophagectomy [@melis114]

## Smoking Cessation

Randomized trial of smoking cessation [@lindstrom739]

## Preoperative counseling

## Preoperative pulmonary function testing

Society for Thoracic Surgery database dictates pulmonary function testing on all patients prior to esophagectomy

## Pre-habilitation

General references in abdominal and cancer surgery - at least 4 weeks of rehabilitation are superior to postoperative rehabilitation [@gillis391]

Prehabilitation review by expert panel [@carli49]

Implementation of a respiratory care intervention consisting of incentive spirometry, coughing, oral care, patient education, ambulation, and head of bed elevation for general and vascular surgery patients was associated with a significant decrease in rates of pneumonia and re-intubation[@cassidy740]

McGill University study [@minnella1081] of 51 patients undergoing esophageal surgery randomized to preoperative prehabilitation vs none. Improvement seen in six-minute walk test, but no difference in complications or operative mortality.

on the return of functional activity after a major surgical procedure. Hence, efforts to optimize functional capacity prior to surgery have shown improved outcomes for some abdominal and oncologic surgeries \[20\]. A multimodal approach termed as 'prehabilitation' comprising nutritional supplementation, psychological counselling, medical optimization, and a structured exercise program involving both aerobic and strengthening activity has been proposed to improve outcomes \[21\]. Respiratory optimization with deep breathing exercises, spirometry, and inspiratory muscle training decreases pulmonary complications \[22\]. Studies have shown that prehabilitation reduces anxiety, depression and fatigue, and improves the quality of life \[23\]. Preliminary results from a recently concluded study \[24\] on prehabilitation for esophageal surgery demonstrated improvement in functional capacity; however, the impact on postoperative outcomes needs to be evaluated by further ongoing studies \[25\]. Extrapolation from studies on other abdominal surgeries \[20\] suggests that at least 4 weeks of preoperative prehabilitation is better than postoperative rehabilitation to influence outcomes. As most patients with operable esophageal cancer would receive neoadjuvant treatment, it would be opportunistic to use this preoperative window to initiate prehabilitation.

A feasibility trial of prehabilitation before oesophagogastric cancer surgery using a multi-component home-based exercise programme: the ChemoFit study.[@chmelo173]

The Role of Prehabilitation in Modern Esophagogastric Cancer Surgery: A Comprehensive Review.[@bausys2096]

Prehab [@gillis391]

# Minimally-invasive techniques

[@kauppila1131] [@lv6751] [@nagpal1621] [@sgourakis3031] TIME trial [@straatman232] MIRO trial [@briez310] MiRO trial[@nuytens232]

## VTE

American College of Chest Physicians guidelines[@goulde227S]

Survey of VTE esohpagectomy - [@zwischenberger489] tzeng ward martin

*Should we administer preoperative heparin routinely?*

*Duration of prophylactic anticoagulation after hospital discharge?*

*Resumption of anticoagulation in the chronically-anticoagulated patient?*

## Carbohydrate loading

Systematic review [@bilku15]

# Intraoperative Care

## Lung-protective anesthesia

Low tidal volume in abdominal surgery [@futier428] Low tidal volume in MIE [@shen1267]--- zhong, wu,wang,fent JTCVS

[@neto272] [@michelet911]

## Early extubation

## Intraoperative fluid management

[@taniguchi184] [@varadhan488]

Standardized hemodynamic protocols [@klevebroS692]

## Regional analgesia

PROSPECT pain management after VATS: [@feray311]

Review of paravertebral vs epidural analgesia for thoracotomy [@dinge96233]

Reiew of paravertebral and epidural analgesia for thoracic surgery [@baidya626]

Review of regional anesthesia for thoracotomy [@joshi1026]

Cochrane review of paravertebral block vs epidural in patients undergoing thoracotomy [@yeungCD009121]---Yeung JH, Gates S, Naidu BV, Wilson MJ, Gao Smith F.

Paravertebral vs epidural [@dinge96233]

Pain management [@visser1]

## Avoidance of hypothermia


\newpage

## Jejunostomy

Retrospective analysis suggests a benefit from jejunostomy placed at the time of esophagectomy.[@watson421]\*

**Question:**

1 - What is a reasonable approach to starting tube feeds in a postoperative patient?

2 - Tube feed formulae for the morbidly obese patient?

3 - What criteria (diarrhea/bloating) should be used to change in tube feed formula?

4 - Feeding plan after esophagectomy (ie transition from tube feeds to oral nutrition)

### Hazards of feeding jejunostomy

Jejunal necrosis

Jejunostomy infection

(Who might not need a jejunostomy at the time of espohagectomy?)

### Early feeding after esophagectomy

Nutrient II trial [@berkelmans41] randomized 132 patients after esophagectomy between oral nutrition on postoperative day 1 vs postoperative day 5. They found no differences in anastomotic leakage and pneumonia, although their relatively high rates of each complication (17% and 30%) makes the study difficult to interpret.

A single-center trial of early feeding randomized 196 patients to direct oral feeding on postoperative day 1 or feeding on postoperatve day 5. The early feeding group had shorter length of stay (8 vs 10 days) and shorter time to functional recovery (7 vs 9 days)[@fransen919].

### Diabetic management with feeding jejunostomy


Intraoperative hypothermia is associated with increased risk of postoperative infections.  Active warming with forced air blankets are routinesly used (eg upper and lower-body Bair Huggers where possible)


# Postoperative Care

## NG decompression

The ERAS society guidelines recommend routine nasogastric decompression post-esophagectomy, but with early removal, on day 2, when clinically appropriate \[10\].

[@weijs1]



## Chest drainage

[@refai820] - early chest tube removal

The right chest is routinely drained to remove fluid and evacuate air (particularly in patients with intrapleural adhesive disease).  A transhiatal Blake or JP drain can perform much of this function with less discomfort

** Transhiatal drainage of the right chest is performed with a 19FR Blake drain labeled JP2)**

## Atrial fibrillation prophylaxix

Diltiazem

Beta Blockade

Amiodarone - Tisdale randomized trial

Magnesium

## Atrial fibrillation prophylaxix

New onset atrial fibrillation occurs in up to 20% of patients after esophagectomy and its incidence appears to increase with age.

The Society for Thoracic Surgery recommends several options for atrial fibrillation prophylaxis:

- Metoprolol
- Cardiazem
- Amiodarone


## Proton pump inhibitors

A Swedish trial of 80 patients after esophagectomy randomized them to postoperative treatment with b.i.d proton pump inhibitors for one year after surgery vs none found a reduced incidence of anastomotic stricture[@johansson667].Benign anastomotic strictures developed in 5/39 (13%) patients in the PPI group and in 18/40 (45%) in the control group

## Evaluation for anastomotic leak

### Drain amylase

Tang H, Xue L, Hong J, Tao X, Xu Z, Wu B. A method for early diagnosis and treatment of intrathoracic esophageal anastomotic leakage: prophylactic placement of a drainage tube adjacent to the anastomosis. J Gastrointest Surg. 2012;16:722–727.





## Pyloric drainage

The benefit of the method of pyloric drainage is controversial[@akkerman1512] Pyloric drainage appears to reduce the risk of early postoperative delayed gastric emptying but does not appear to affect other outcomes [@urschel160]

## Removal of urinary cather

(Flomax can't be given via jejunostomy)

### Drain amylase

Monitoring of drain amylase is a cost-effective a sensitive method of detection of anastomotic leak [@linden1794] [@baker181]


### Markers of systemic inflammation

#### WBC

### CT Esophagram

## Evaluation of swallowing function

## ERAS in other disease sites

Colorectal ERAS Canarian impact multisite [@thanh415]--wasylak, faris

CanadianN[@nelson1092]

## Surgeon Volume and survival

[@markar718]
