---
title: "Esophageal Perforation"
format: 
  revealjs:
    slide-number: c/t
    width: 1600
    height: 900
    logo: "atriumlogo.jpg"
    footer: "[Get started with Quarto](https://rstudio-conf-2022.github.io/get-started-quarto/)"
    #css: ["theme/theme.css"]
    theme: default
      
    echo: false
editor: visual
---

# Esophageal Perforation

Perforation can occur through mucosa, muscle, or adventitia. The esophagus lacks a serosal layer, which makes it more susceptible to perforation. Once perforation occurs, gastric contents and bile enter the mediastinum, and necrotizing mediastinitis develops. Polymicrobial invasion by bacteria, such as Staphylococcus, Pseudomonas, Streptococcus, and Bacteroides, occurs within 12 hours, and the infection may result in fluid sequestration, sepsis, and death.

# Etiology

-   Iatrogenic, most frequently endoscopy. The most common site of injury is the cricopharyngeus, but when esophageal dilatation is performed, the site of perforation is at the stricture of the original disease.

-   Postemesis, such as Boerhaave syndrome. Other causes of a sudden rise in intraesophageal pressure include weightlifting, laughing, hyperemesis gravidarum, and seizures. Spontaneous rupture almost always occurs on the left side of the distal third of the esophagus.

-   Trauma (penetrating and blunt).

-   Steering wheel injury

-   Pharmacologic agents: KCl, NSAIDs

-   Caustic injury

# Diagnosis (Physical Findings)

-   PE crepitus chest, neck, or face; neck swelling; epigastric tenderness; and nasal voice. Sometimes results are normal.

# Diagnostic Tests

CXR: Pleural effusion, pneumomediastinum, and subcutaneous

CT Esophagram

Upper GI with gastrograffin (?)

# Treatment

-Treatment of contamination -Wide local drainage -Source control -Enteral feeding access

# Surgical Options

-   High perforations (cerviaL)
-   Mid-esohageal
-   Lower esophagus

# Surgical Principles

-   Myotomy for exposure and debridement
-   Primary repair
    -   Small injuries
    -   Two layers
    -   Tissue flap (intercostal, pericardial flap, pleura, omentum)
-   T tube for larger injuries
-   Esophageal exclusion with cervical esophagostomy

# Nonoperative Management

-   Clinical stability, with minimal signs of sepsis or systemic inflammatory response on presentation. Patients must remain this way; they should have a reliable examination and constant monitoring for any changes in clinical status.
-   Instrumental perforations in which patients have been nil per os (NPO; nothing by mouth) and in which the perforation is detected early or "tolerance" develops to the perforation without the need for surgery
-   Perforation contained within the neck or mediastinum with no extravasation and no signs of crepitus, pneumothorax, or pneumoperitoneum

# Non-operative management

-   NPO status
-   IV fluid resuscitation
-   Antibiotics (including antifungal)
-   Nutrition (enteral or parenteral)
