---
title: "Frailty Index"
editor: visual
bibliography: zotero.bib
---

# Frailty

Frailty is "a biological syndrome of decreased reserve and resistance to stressors, resulting from cumulative decline across multiple physiologic systems, and causing vulnerability to adverse outcomes" Fried LP, Tangen CM, Walston J, et al. Frailty in older adults: evidence for a phenotype. J Gerontol A Biol Sci Med Sci 2001;56:M146-56

# Frailty Scores

## eFrailty Index

EFI_SCORE and EFI_PERCENTILE now available in Translational Data Warehouse [@rockwood722] and [@clegg353]

Brief clinical instrument to classify frailty in the elderly Lancet 1999 205 rockwood

Frailty and hematologic malignancies [@abel515]

eFI calculated based upon 36 deficits which can be abstracted from the electronic medical record [@clegg353]

Frailty among VA patients [@orkaby1257]

WFU: eFI using Epic data in Medicare ACO [@pajewski1771]

eFI using epic data for preoperative risk stratification in vascular surgery [@callahan1357]

VA-FI Frailty Index [@dumontier3053]

Learning Health System and BioInformatics [@kohne10259]

## NSQIP Modifided Frailty Index

Paraesophageal hernia repair[@chimukangara2509]. Multivariable regression with mFrailty5, age, ASA: mFrailty5 score \>=2 was significant predictor of mortality

Esophagectomy [@hodari1240a]. Multivariable regression for mortality as an outcome with age, ASA: Only age and mFrailty5 were significant.

mFrailty5 [@subramaniam17] Mortality, readmission, complications. mFrailty5 associated with mortality in General Surgery patients in multivariable model adjuvsted for ASSA, wound class, age, transfer status, emergency status.

mFrailty5 and Colorectal cancer [@mcgovern9] mFrailty5 strongly associated with age. Multivariable analysis with age \<65, 65-75, and 75+ and mFI5 (0/1/\>2) parsimonious model includes sex, systemic inflammation, and mFailty5

mFrailty5 and Colorectal cancer [@mcgovern9] mFrailty5 strongly associated with age. Multivariable analysis with age \<65, 65-75, and 75+ and mFI5 (0/1/\>2) parsimonious model includes sex, systemic inflammation, and mFailty5 (but not age)

Colorectal cancer over age 65 [@simon1363] mFrailty5 correlated with mortality on univariate analysis and also after adjustment

MFI and mortality after hip fracture [@daddimani30951] Mortality at one year association reported for mFrailty5 but not in multivariable. No association between age and mortality at one year.

NLP of unstructured EHR data to identify geriatric syndrome [@kharrazi1499]

mFrailty5 \[@mosquera272\]

mFrailty5 and Colorectal cancer [@al-khamis1192]]

panayi 393. [@panayi393]

Velanovich V, Antoine H, Swartz A, Peters D, Rubinfeld I. Accumulating deficits model of frailty and postoperative mortality and morbidity: its application to a national database. J Surg Res. 2013;183(1):104–10. [@velanovich104]

Colorectal cancer over age 65 [@simon1363] mFrailty5 correlated with mortality but no multivariate analysis was done to separate age from mFrailty5

Lascano D, Pak JS, Kates M, et al. Validation of a frailty index in patients undergoing curative surgery for urologic malignancy and comparison with other risk stratification tools. Urol Oncol. 2015;33(10):426.e1–12. [@lascanoe1]

Frailty is a better predictor than age for outcomes in geriatric patients with rectal cancer undergoing proctectomy. [@miller504]

NSQIP Dat for coletomy CABG PD, pneumonectomy, esophagecgtomy 2002-2017 [@wane721] compared mFrailty5 with others and concluded it was "ineffective" in predicting 30=day morbidity and mortality

Colorectal Columbia University:mFrailty5 in predicting outcomes. "predictive ability is enhanced when other patietn-specific risk factors are incorporated [@keller1396]

Traven SA, Reeves RA, Althoff AD, et al. New five-factor modified frailty index predicts morbidity and mortality in geriatric hip fractures. J Orthop Trauma. 2019;33:319–323. 23. [@traven319]

Traven SA, Reeves RA, Sekar MG, et al. New 5-factor modified frailty index predicts morbidity and mortality in primary hip and knee arthroplasty. J Arthroplasty. 2019;34:140–144. 24. [@traven319]

Weaver DJ, Malik AT, Jain N, et al. The Modified 5-item frailty index: a concise and useful tool for assessing the impact of frailty on postoperative morbidity following elective posterior lumbar fusions. World Neurosurg. 2019;124:e626–e632. [@weavere626]

# Comprehensive Geriatric Assessment

## CARE Survey

CARE survey is a modified version of the original Cancer and Aging Research Group geriatric assessment, augmented to streamline completion and to aid integration into routine oncologic clinical practice. The CARE survey measures activities of daily living (ADLs), instrumental ADLs (iADLs), the ability to walk 1 block, the number of falls within 6 months, nutrition, comorbid conditions, cognitive complaints, anxiety, depression, social support, social activities, and self-rated Eastern Cooperative Oncology Group performance status. Domain-specific cutoffs were used in accordance with prior literature.21, 23-25 Frailty was reported using the CARE Frailty Index based on the principles of deficit accumulation, as previously published.26, 27 In brief, the CARE Frailty Index includes 44 geriatric assessment variables identified as health deficits from the CARE survey, each of which is scored as 0 (no deficit) or 1 (deficit present) (see Supporting Methods). These values were then combined and divided by the overall number of deficits assessed (range, 0-1) and categorized as robust (0-0.2), prefrail (0.2-0.35), and frail (\>0.35).26 In addition, the CARE survey incorporates the Patient-Reported Outcomes Measurement Information System (PROMIS) 10-item global health questionnaire to assess HRQoL, which includes physical and mental health subscales.28, 29

Prognostic scales for cancer: France: [@canoui-poitrine2236] 510 patients with cancer evaluated with multiple prognostic scales including CCI and Elixhauser. Only Cumulative Illness Rating Scale for Geriatics (CIR-G) was predictive of one-year mortality.

## SARC-F screening

Ida S, Kaneko R, Murata K. SARC-F for screening of sarcopenia among older adults: a meta-analysis of screening test accuracy. J Am Med Dir Assoc. 2018;19:685-689.

Woo J, Leung J, Morley JE. Validating the SARC-F: a suitable community screening tool for sarcopenia? J Am Med Dir Assoc. 2014;15:630-634.

Malmstrom TK, Morley JE. SARC-F: a simple questionnaire to rapidly diagnose sarcopenia. J Am Med Dir Assoc. 2013;14:531-532.

Malmstrom TK, Miller DK, Simonsick EM, Ferrucci L, Morley JE. SARC-F: a symptom score to predict persons with sarcopenia at risk for poor functional outcomes. J Cachexia Sarcopenia Muscle. 2016;7:28-36.

The SARC-F (strength, assistance with walking, rising from a chair, climbing stairs, and falls) is a surrogate assessment tool, with a total score of ≥4 suggestive of sarcopenia.35 A person may also be considered as "probable sarcopenia" if SARC-F is positive and handgrip strength is low (Asian Working Group for Sarcopenia criteria: \<28 kg for men, \<18 kg for women).

# Reporting

Benchimol EI, Smeeth L, Guttmann A, et al. The REporting of studies Conducted using Observational Routinely-collected health Data (RECORD) statement. PLoS Med. 2015;12(10):e1001885. https://doi.org/10.1371/journal.pmed.1001885 . - DOI - PubMed - PMC

# Palliative Care consultations

VA System: [@sullivan1702] Lung Cancer - palliative care consultation 31-365 days after dx led to increased survival

# Enteral nutrition in cancer patients

In 347 stage IV gastric cancer patients at high nutrition risk and receiving palliative CT, nutritional support was associated with a survival benefit 39.Qiu M, ZhouYX, Jin Y, Nutrition support can bring survival benefit to high nutrition risk gastric cancer patients who received chemotherapy. Support Care Cancer. 2015: 23; 1933. -9 Esophageal cancer patients RCT enteral therapy vs oral nutrition [@lyu839516]

# Physiometric Evaluation

## Pulmonary function testing.

Investigators in Kobe, Japan examined functional testing in 104 patients undergoing esophagectomy [@makiura430] , 2016, 2016}. Patients were designated as frail based upon hand-grip strength \<26kg and sarcopenia as measured radiographically. Sarcopenia was diagnosed in 29 patients, in whom the rate of pneumonia was 38%, compared with 17% in the remaining patients.

## Hand Grip Strength

Kilgour 2013 p 1894 Veni 2018 and Boyas

## 6 minute walk test

Gait speed and mortality in older adults [@studenski50]

### Short Physical Performance Battery

SPPB predicts survival and nursing home admission [@guralnikM85]

## Stair-climbing

Stair Climbing is strong predictor of perioperative morbidity[@reddy559]

## Timed up and go

?Part of Fried scale? [@podsiadlo142]

# Sarcopenia and Lung Cancer

PNI and lung cancer meta-analysis [@shaoe31113]
