---
title: "Geriatric Surgery"
editor: visual
bibliography: zotero.bib
---

# Risk Assessment for Cancer Surgery

Mortality should be reported at 90 days Mayo SC, Shore AD, Nathan H, Edil BH, Hirose K, Anders RA, et al. Refining the definition of perioperative mortality following hepatectomy using death within 90 days as the standard criterion. HPB (Oxford). 2011;13:473--82

Venkat R, Puhan MA, Schulick RD, Cameron JL, Eckhauser FE, Choti MA, et al. Predicting the risk of perioperative mortality in patients undergoing pancreaticoduodenectomy: a novel scoring system. Arch Surg. 2011;146:1277--84 

Bryant AS, Rudemiller K, Cerfolio RJ. The 30- versus 90-day operative mortality after pulmonary resection. Ann Thorac Surg. 2010;89: 1717--22; discussion 1722--3

Preoperative Assessment of Cancer in the Elderly (PACE): Audisio RA, Pope D, Ramesh HS, Gennari R, van Leeuwen BL, West C, et al. Shall we operate? Preoperative assessment in elderly cancer patients (PACE) can help. A SIOG surgical task force prospective study. Crit Rev Oncol Hematol. 2008;65:156--63 

Heriot AG, Tekkis PP, Smith JJ, Cohen CR, Montgomery A, Audisio RA, et al. Prediction of postoperative mortality in elderly patients with colorectal cancer. Dis Colon Rectum. 2006;49:816--24 Pope D, Ramesh H, Gennari R, Corsini G, Maffezzini M, Hoekstra HJ, et al. 

Pre-operative assessment of cancer in the elderly (PACE): a comprehensive assessment of underlying characteristics of elderly cancer patients prior to elective surgery. Surg Oncol. 2006;15:189--97

