---
title: "GI Cancer Disparities"
editor: visual
bibliography: zotero.bib
---

## Disparities in esophageal cancer

SEER Trends in esophageal cancer: [@corona883] The study included 19,257 EAC cases and 15,162 ESCC cases. EAC mortality increased significantly overall and in non-Hispanic Whites from 1993 to 2012 and from 1993 to 2010, respectively. EAC mortality continued to rise among non-Hispanic Blacks (NHB) (APC = 1.60, p = 0.01). NHB experienced the fastest decline in ESCC mortality (APC = - 4.53, p \< 0.001) yet maintained the highest mortality at the end of the study period. Proportions of late stage disease increased overall by 18.5 and 24.5 percentage points for EAC and ESCC respectively; trends varied by race/ethnicity.

SEER *no survival difference based upon race* [@tramontano2880] T1-3N0M0 adenocarcinoma and squamous cell cancer patients diagnosed between 2003 and 2011. Among 2025 patients, 87.9% were White and 12.1% were Nonwhite. Median survival was 18.7 months for Whites vs 13.8 months for Nonwhites (p = 0.01). In the unadjusted model, Nonwhite patients had higher risk of mortality (HR = 1.29, 95% CI 1.11-1.49, p \< 0.0001) when compared to White patients; however, in the Cox regression adjusted model there was no significant difference (HR = 0.94, 95% CI 0.80-1.10, p = 0.44). Surgery, chemotherapy, younger age, lower T stage, and lower Charlson comorbidity score were significant predictors in the full adjusted model. Differences in mortality risk by race/ethnicity appear to be largely explained by additional factors.

NCDB comparison of hospitals [@sridhar1472] NCDB esophageal cancer 2004-2013. Treating facilities were categorized according to their relative burden of uninsured or Medicaid-insured patients. Hospitals with low (LBH), medium (MBH), and high (HBH) safety-net burden were compared with respect to patient demographics, disease and treatment characteristics, and survival. 56,115 patients from 1,215 facilities. HBH treated a greater proportion of racial and ethnic minorities and patients with lower socioeconomic status. Patients at HBH presented at later stages and received primary surgical therapy less often than at MBH and LBH. Survival for patients with esophageal adenocarcinoma did not differ significantly between HBH and LBH after adjusting for age, sex, race, ethnicity, income, comorbidity, stage, histologic type, tumor location, facility type, insurance status, and treatment modality (hazard ratio, 1.06; 95% confidence interval, 0.99 to 1.14; p = 0.093). *HBH were associated with a higher mortality risk than LBH for patients with squamous cell carcinoma (hazard ratio, 1.11; 95% confidence interval, 1.02 to 1.20; p = 0.014).* There is a mortality risk for patients with squamous cell carcinoma, but not for adenocarcinoma at HBH compared with LBH. **Could preferential use of High Burden Hospitals by racial minorities account for their worse outcomes?**

Michigan Cancer Registry *marital status at the time of diagnosis* [@paniaguacruze498] 88.4% of our patients were White and 11.6% were Black. A significantly higher number of White patients were married when compared with Blacks (62.9% v 31.8%, respectively; P \< .0001). There was no significant difference in cancer staging between the 2 groups (P = .0671). Married Blacks had similar rates of esophagectomy, chemotherapy, and radiation as married Whites. Both single groups had lower rates of esophagectomy and chemotherapy than married Whites, but single Blacks were the least likely to undergo esophagectomy. Single patients were more likely to refuse treatment.Marital status differs significantly in Black and White patients with esophageal cancer and may help explain racial disparities in cancer care. Further research is needed to explore reasons for care underutilization in single patients and whether these differences translate into clinical outcomes. **Marital status at dx is a field in the CR Star data!!**

NCDB [@schlottmanndoz045] NCDB Stage I-III esophageal cancer 2004-2015. Multivariable logistic regression models were used to determine the odds of being offered no treatment at all and surgical treatment across race, primary insurance, travel distance, income, and education levels. **but was histology included in their model?** Multivariable Cox proportional hazards models were used to compare 5-year survival rates across different treatment modalities. A total of 60,621 esophageal cancer patients were included. Black patients, uninsured patients, and patients living in areas with lower levels of education were more likely to be offered no treatment. Similarly, black race, female patients, nonprivately insured patients, and those living in areas with lower median residential income and lower education levels were associated with lower rates of surgery. Patients receiving surgical treatment, compared to both no treatment and definitive chemoradiation, had significant better long-term survival in stage I, II, and III esophageal cancer. **Is the negative effect on survival due to race or insurance status/geography?**

[@savitch581] NCDB stage I-III esophageal cancer 2004-2015 matched cohorts White:Black. 60,041 patients were included (4402 black; 55,639 white). After 1:1 matching, there were 5858 patients. For all stages, significantly fewer black than white patients received surgery. Black race independently conferred lower likelihood of receiving surgery in single-level multivariable analysis (OR (95% CI); stage I, 0.67 (0.48-0.94); stage II, 0.76 (0.60-0.96); stage III, 0.62 (0.50-0.76)) and after controlling for hospital random effects. Hospital-level random effects accounted for one third of the unexplained variance in receipt of surgery. Risk-adjusted 1-, 3-, and 5-year mortality was higher for patients who did not undergo surgery. **Did this study account for histology? What about SES?**

Smae study, different journal: [@revels1136] NCDB 2004-2015 Stage I-III esophageal cancer. Matched patient cohorts were created to reduce confounding. Multivariate logistic regression was used to identify factors associated with receipt of surgery. Multi-level modeling was performed to control for random effects of individual hospitals on surgical utilization.Total of 60,041 patients were included (4402 black; 55,639 white). After 1:1 matching, there were 5858 patients evenly distributed across race. For all stages, significantly fewer black than white patients received surgery. Black race independently conferred lower likelihood of receiving surgery in single-level multivariable analysis (OR (95% CI); stage I, 0.67 (0.48-0.94); stage II, 0.76 (0.60-0.96); stage III, 0.62 (0.50-0.76)) and after controlling for hospital random effects. Hospital-level random effects accounted for one third of the unexplained variance in receipt of surgery. Risk-adjusted 1-, 3-, and 5-year mortality was higher for patients who did not undergo surgery. Looks identical to [@savitch581]

[@swords333] NCDB 2003-2011 Stage I-III esophageal cancer. Median income by zip code and proportion of the zip code residents without a high school diploma were grouped into income and education quartiles, respectively and used as surrogates for SES. Of 11,599 esophagectomy patients who met study criteria, 3,503 (30.2%) were in the highest income quartile, 2,847 (24.5%) were in the highest education quartile, and 610 patients (5%) were black. Before adjustment for SES, black patients had worse overall survival than white patients (median survival 23.0 versus 34.7 months, log rank p \< 0.001), and overall, survival times improved with increasing income and education (p \< 0.001 for both). After adjustment for putative prognostic factors, \*SES was associated with overall survival, whereas race was not.\*\*

[@savitch581] NCDB 2004-2015 Stage I-III esophgeal cancer. Matched patient cohorts were created to reduce confounding. Multi-level modeling was performed to control for random effects of individual hospitals on surgical utilization. Total of 60,041 patients were included (4402 black; 55,639 white). After 1:1 matching, there were 5858 patients evenly distributed across race. For all stages, significantly fewer black than white patients received surgery. Black race independently conferred lower likelihood of receiving surgery in single-level multivariable analysis (OR (95% CI); stage I, 0.67 (0.48-0.94); stage II, 0.76 (0.60-0.96); stage III, 0.62 (0.50-0.76)) and after controlling for hospital random effects. **Hospital-level random effects accounted for one third of the unexplained variance in receipt of surgery**. Risk-adjusted 1-, 3-, and 5-year mortality was higher for patients who did not undergo surgery. CONCLUSION: Black patients with esophageal cancer are at higher risk of mortality compared to white patients. This increased risk may be influenced by decreased likelihood of receiving surgical intervention for resectable disease, in part because of **between-hospital differences**. Improving access to surgical care may improve disparities in esophageal cancer survival. \*\*Another way of studying access to surgical care - this time at the facility level. Further su\*pport for the theme that access to surgery is barrier to optimal esophageal cancer care.\*\*

[@erhunmwunsee234] NCDB stage I-III 2003-2011. Median income by zip code and proportion of the zip code residents without a high school diploma were grouped into income and education quartiles, respectively and used as surrogates for SES. The association between race and overall survival stratified by SES is explored. Of 11,599 esophagectomy patients who met study criteria, 3,503 (30.2%) were in the highest income quartile, 2,847 (24.5%) were in the highest education quartile, and 610 patients (5%) were black. Before adjustment for SES, black patients had worse overall survival than white patients (median survival 23.0 versus 34.7 months, log rank p \< 0.001), and overall, survival times improved with increasing income and education (p \< 0.001 for both). After adjustment for putative prognostic factors, SES was associated with overall survival, whereas race was not. *Did study include histology in their model?*

[@okerekedoab083] NCDB 2004-2017: 127,098 patients. All minority groups were more likely to be diagnosed at advanced stages versus Caucasians after adjusting for covariates (African American OR-1.64 \[95% confidence interval 1.53-1.76\], Hispanic OR-1.19 \[1.08-1.32\], Asian OR-1.78 \[1.55-2.06\]). After adjustment, all minorities were less likely at every stage to receive surgery. Despite these disparities, Hispanics and Asians had improved survival compared with Caucasians. African Americans had worse survival. Racial disparities for receiving surgery were present in both academic and community institutions, and at high-volume and low-volume institutions. Surgery partially mediated the survival difference between African Americans and Caucasians (HR-1.13 \[1.10-1.16\] and HR-1.04 \[1.02-1.07\], without and with adjustment of surgery).

[@sridhar1472] NCDB esophageal cancer 2004-2013. Treating facilities were categorized according to their relative burden of uninsured or Medicaid-insured patients. Hospitals with low (LBH), medium (MBH), and high (HBH) safety-net burden were compared with respect to patient demographics, disease and treatment characteristics, and survival. 56,115 patients from 1,215 facilities. HBH treated a greater proportion of racial and ethnic minorities and patients with lower socioeconomic status. Patients at HBH presented at later stages and received primary surgical therapy less often than at MBH and LBH. Survival for patients with esophageal adenocarcinoma did not differ significantly between HBH and LBH after adjusting for age, sex, race, ethnicity, income, comorbidity, stage, histologic type, tumor location, facility type, insurance status, and treatment modality (hazard ratio, 1.06; 95% confidence interval, 0.99 to 1.14; p = 0.093). HBH were associated with a higher mortality risk than LBH for patients with squamous cell carcinoma (hazard ratio, 1.11; 95% confidence interval, 1.02 to 1.20; p = 0.014). Conclusions: There is a mortality risk for patients with squamous cell carcinoma, but not for adenocarcinoma at HBH compared with LBH.

California Cancer Registry [@tran3] Esophageal cancer cases 2004-2010. African Americans and Hispanics were more likely to be in the lower SES strata and less likely to receive surgery than Caucasians in this cohort. The proportion of patients receiving chemotherapy and radiotherapy was similar across different racial/ethnic groups. After adjustment for stage, grade, **histology**, treatments, and SES in multivariate analyses, the mortality risk in African Americans (hazard ratio \[HR\] 0.96, 95% confidence interval \[CI\] 0.85-1.07) and Hispanics (HR 0.96, 95% CI 0.89-1.07) did not differ from Caucasians (HR = 1.00, referent), with histology, SES, and **surgery** largely accounting for unadjusted OS differences. We also observed that African American men had higher adjusted risk of death relative to Caucasian men (HR 1.24, 95% CI 1.07-1.42), but this effect was not observed for African American women compared to Caucasian women (HR 1.12, 95% CI 0.94-1.35). CONCLUSIONS: Race is not an independent risk factor for OS in our population-based analysis of EC cases. Rather, observed differences in OS by race/ethnicity result from differences in cancer histology, SES, surgery, and gender. *Sounds like receipt of surgery remains disparate based upon race and accounts for some differences in outcome*

## Disparities in access to surgical care

North Carolina [@wong239] compared per capita rate of surgery in 5 high-resource counties with 5 low-resource counties using is data from the Health Cost and Utilization Project State Inpatient Database from 2016. Using the surgical rate observed in the 5 highest-ranked counties (HRCs), the expected surgical rate in the 5 lowest-ranked counties (LRCs) in North Carolina were calculated. Patients 18 years and older who underwent an inpatient general surgery procedure and patients who underwent emergency inpatient cholecystectomy, herniorrhaphy, or bariatric surgery in 2016 were included. The primary outcome was the proportional surgical ratio (PSR), which was the disparity in surgical access defined as the observed number of surgical procedures in the 5 LRCs relative to the expected number of procedures using the 5 HRCs as the standardized reference population. In 2016, approximately 1.9 million adults lived in the 5 HRCs, while approximately 246 854 lived in the 5 LRCs. A total of 28 924 inpatient general surgical procedures were performed, with 4521 being performed in those living in the 5 LRCs and 24 403 in those living in the 5 HRCs. The rate of general surgery in the 5 HRCs was 13.09 procedures per 1000 population. Using the 5 HRCs as the reference, the PSR for the 5 LRCs was 1.40 (95% CI, 1.35-1.44). For emergent/urgent cholecystectomy, the PSR for the 5 LRCs was 2.26 (95% CI, 2.02-2.51), and the PSR for emergent/urgent herniorrhaphy was 1.83 (95% CI, 1.33-2.45). Age-adjusted rate of obesity (body mass index \[calculated as weight in kilograms divided by height in meters squared\] greater than 30), on average, was 36.6% (SD, 3.4) in the 5 LRCs vs 25.4% (SD, 4.6) in the 5 HRCs (P = .002). The rate of bariatric surgery in the 5 HRCs was 33.07 per 10 000 population with obesity. For the 5 LRCs, the PSR was 0.60 (95% CI, 0.51-0.69). **Could we use this same database for esophagectomy? Need to figure out whether patients that have surgery in an read different from where they live are scored as their county of residence or county where surgery was done**

[@degajer276]

### Body composition and Racial/Ethnic differences

Age - Sex - Race body composition standard Curves[@magudia319]

> Background Although CT-based body composition (BC) metrics may inform disease risk and outcomes, obtaining these metrics has been too resource intensive for large-scale use. Thus, population-wide distributions of BC remain uncertain. Purpose To demonstrate the validity of fully automated, deep learning BC analysis from abdominal CT examinations, to define demographically adjusted BC reference curves, and to illustrate the advantage of use of these curves compared with standard methods, along with their biologic significance in predicting survival. Materials and Methods After external validation and equivalency testing with manual segmentation, a fully automated deep learning BC analysis pipeline was applied to a cross-sectional population cohort that included any outpatient without a cardiovascular disease or cancer who underwent abdominal CT examination at one of three hospitals in 2012. Demographically adjusted population reference curves were generated for each BC area. The z scores derived from these curves were compared with sex-specific thresholds for sarcopenia by using χ2 tests and used to predict 2-year survival in multivariable Cox proportional hazards models that included weight and body mass index (BMI). Results External validation showed excellent correlation (R = 0.99) and equivalency (P \< .001) of the fully automated deep learning BC analysis method with manual segmentation. With use of the fully automated BC data from 12 128 outpatients (mean age, 52 years; 6936 \[57%\] women), age-, race-, and sex-normalized BC reference curves were generated. All BC areas varied significantly with these variables (P \< .001 except for subcutaneous fat area vs age \[P = .003\]). Sex-specific thresholds for sarcopenia demonstrated that age and race bias were not present if z scores derived from the reference curves were used (P \< .001). Skeletal muscle area z scores were significantly predictive of 2-year survival (P = .04) in combined models that included BMI. Conclusion Fully automated body composition (BC) metrics vary significantly by age, race, and sex. The z scores derived from reference curves for BC parameters better capture the demographic distribution of BC compared with standard methods and can help predict survival. Investigators at the University of Illinois {@jang557} examined the change in skeletal muscle index during cancer treatment among 212 patients. Among 132 non-Hispanic Black patients, muscle loss during therapy was greater than non-Hispanic White and Other (Asian + Hispanic) (Odds Ratio 3.29 p=0.004). The loss was highest in Black rectal cancer patients (11 units of SMI loss cm2/m2) vs White rectal Cancer (8 cm2/m2). Loss among colon cancer patients was higher in Black patients ( 5.5 cm2/m2) than in White patients (2.5 cm2/m2). Prior to treatment, Blacks had higher SMI than White (similar to findings of Xaio 2019)

Data from Kaiser [@xaio615] examined 3263 patients with non-metastatic colorectal cancer. Black patients had higher lower rates of sarcopenia according to the definition of Prado et al. Patients with higher neutrophil-lymphocyte ratio had higher risk of muscle abnormality. CT scan at L3 was analyed to determine SMI,IMAT,VAT,SAT and TAT (=VAT+SAT+IMAT) using SliceOMatic. Threshold values determined for optimal stratification (cf [@martin153] [@prado639]

### Body composition in Colorectal cancer

Muscle radiodensity and mortality in patients with colorectal cancer [@kroenke3008]

French investigators studied 51 patients with mCRC and found sarcopenia in 70% (39% of women and 82% of men). In multivariate analysis including age, sex, BMI, sarcopenia, SAT, and VAT, the only factor associated with Grade 3-4 toxicities was sarcopenia (odds ratio = 13.55; 95% confidence interval \[1.08; 169.31\], P = 0.043).{@barrett_Nutritionand Cancer v6 2014(4)}

Xaio fou

### Body composition and therapy of advanced GI Cancers

### Inflammation in COlorectal Cancer

Kaiser: Sarcopenia and inflammation in colorectal cancer. [@felicianoe172319]

PMID 24122750

PMID 24866483

Low muscle mass has been shown to be associated with poor prognosis cancer patients.[@martin1539] This may be due to overal frailty or low muscle mass may lead to increased toxicity from chemotherapy due to pharmacokinetic mechanism. 5-FU is hydrophilic and it volume of distribution includes the muscle compartment, while oxaliplatin is hydrophobic, with distribution in the fat compartment[@bozzetti2107].

In addition, loss of muscle mass during chemotherapy for advanced cancers is a poor prognosticator.

Blauhoff [@blauwhoff-buskermolen1339] studis 67 patients with metastatic colorectal cancer. Muscle area on CT decreased by 6.1% over 3 months. Patients in the lowest tertile (loss of 9%) had worse survial. Overall survival 17.5 months for first-line chemotherapy and 8.5months for second-line. Baseline muscle density was predictive of survival on multivariable analysis, but low SMI at baseline was not associatesd with survival. (This may be because sarcopenic obesity is the major risk factor, and there were few obese patients in the study cohort) \>Muscle loss of 9% or more remained independently associated with survival when adjusted for sex, age, baseline lactate dehydrogenase concentration, comorbidity, mono-organ or multiorgan metastases, treatment line, and tumor progression at first evaluation by computed tomography scan (hazard ratio, 4.47; 95% CI, 2.21 to 9.05; P , .001). We found a mean coefficient of variation between observers of 0.6% for skeletal muscle area in a random sample of 20 patients, which is regarded to be low.[@macdonald342]. Changes between the first and second scans were calculated as a rate of change per 3 months, meaning change per first evaluation, to compare with available literature.\[awad74\]\[prado1583\]Relative muscle change per 3 months was categorized into tertiles of muscle change: tertile one, highest muscle loss up to 9%; tertile two, muscle loss of 9% to 1.5%; and tertile three, muscle loss of 1.5% until highest gain in muscle. However, the survival curve of tertile two was not significantly different from the survival curve of tertile three (log-rank P = .961); therefore tertiles two and three were pooled (cutoff, 9% muscle loss).

Awad [@awad74]studies changes in body composition during neodjuvant chemotherapy for esophagogastric cancer.

Kurk [@kurk1033] found that skeletal muscle loss during chemotherapy was associated with decreased progression-free and overall- survival in metastatic colorectal cancer.

> Detailed changes in skeletal muscle mass and body weight during CAIRO3 treatments were previously reported.KurkS, p909, 2018) We additionally analyzed changes in SMI and BMI during these treatments by linear mixed effects models.(Bayar MA,p311,2017) The baseline value of the outcome (SMI/BMI) was included in the outcome vector. Potential confounders were age, sex, lactate dehydrogenase (LDH) levels, best response to initial six cycles CAPOX‐B, resection of the primary tumor, and the number of metastatic sites. The final model was selected based on the Akaike Information Criterion (AIC) and included: treatment arm, time, age, sex, resection primary tumor, and the interaction of treatment arm by time as fixed effects. Modeling time as a random effect did not increase the model fit as indicated by the AIC. To investigate differences in SMI and BMI changes over time between the CAIRO3 treatment arms, we checked the significance of the two‐way interaction including treatment arm by time.

> During p2 (maintenance CAP‐B/observation), again absolute SMI and BMI at the start (t1) of treatment were not associated with early progression and death. In contrast, SMI loss and BMI loss during treatment were associated with early progression and death.

Fogelman [@fogelman307] treated patients undergoing chemotherapy with a novel agent designed to reduce muscle less. CT scans at 2 months were compared with baseline scans prior to chemotherapy.

> Changes in skeletal muscle were determined using routinely acquired CT scans for patients on the study. We calculated skeletal muscle cross-sectional area (cm2) at the third lumbar vertebra (L3). A single slice at the mid-point of L3 was used, preferably a 2.5-mm slice if available, and a 5-mm slice if a 2.5-mm slice was not available. The L3 is a landmark that has been extensively used and validated in studies assessing body composition in cancer patients [@shen2333][@prado269] . Skeletal muscle surface areas were determined using Slice-o-Matic softwareTM, version 4.3 (Tomovision, Montreal, QC, Canada) using pre-established thresholds of Hounsfield units (HU) of −29 to +150 [@mitsiopoulos115]. We additionally evaluated adipose tissue cross-sectional area (subcutaneous, visceral, and intramuscular) in the L3 region as described previously [@mourtzakis997]. Changes in muscle and adipose tissue surface areas over time were determined for each patient from the baseline study to the first CT post treatment, done after 2 months. We looked at muscle loss as a continuous variable and defined "meaningful loss" as greater than a 6 cm2 difference from the baseline to the second scan. We chose this cut point as it is equivalent to 1 kg of skeletal muscle and is associated with physical function (i.e., muscle strength). Additionally, this cut point has been used to investigate significant changes in muscle mass throughout cancer disease trajectory [@shen2333][@frontera1038][@prado1012].

Prado [@prado1012] looked at changes in 1279 CT scans in 368 patients with advanced cancer. The last available interval with CT scans was chosen for comparison. Categorized into stable, gaining, losing for muscle and for adipose tissue. Adipose tissue was ?? sum of visceral adipose tissue and subcutaneous tissue. (**Did not use SMI**). Muscel loss and adipose loss seemed correlated, with larger magnitude of adipose tissue loss at short interval to death. (Authors conclusion that muscle and adipose tissue loss in the past 3 months of life is likely not possible) \>Advanced-cancer patients (n = 368; median survival: 196 d) had a total of 1279 CT images over the course of their disease. With consideration of all time points, muscle loss occurred in 39% of intervals between any 2 scans. However, the overall frequency of muscle gain was 15.4%, and muscle was stable in 45.6% of intervals between any 2 scans, which made the maintenance or gain of muscle the predominant behavior. Multinomial logistic regression revealed that being within 90 d (compared with \>90 d) from death was the principal risk factor for muscle loss (OR: 2.67; 95% CI: 1.45, 4.94; P = 0.002), and muscle gain was correspondingly less likely (OR: 0.37; 95% CI: 0.20, 0.69; P = 0.002) at this time. Sex, age, BMI, and tumor group were not significant predictors of muscle loss or gain. A much higher proportion of men (61%) than women (31%) met the criteria for sarcopenia. Changes in muscle and adipose tissue over time were calculated as the absolute loss or gain of tissue area during each scan interval. The precision error of measurements was \~1.5% [@mourtzakis997] with a minimum detectable change of \~3 cm2. We attributed the change during each interval into the following categories: 1) muscle loss ≥6.0 cm2, 2) stable muscle ±5.9 cm2, or 3) muscle gain ≥6.0cm2. These cutoffs are equivalent to a loss or gain of ≥1 kg of skeletal muscle on a whole-body basis and are associated with alterations in muscle strength [@shen2333][@frontera1038]. For adipose tissue, categories were based on the equivalence of 14.7 cm2 total fat at L3 and 1 kg tissue on a whole-body basis [@shen2333]; therefore, changes during each interval were categorized as 1) adipose tissue loss ≥14.7 cm2, 2) stable adipose tissue ±14.6 cm2, or 3) adipose tissue gain ≥14.7 cm2. CT scans were taken for the diagnosis, confirmation of stage, and follow-up of disease progression and treatment. With the understanding that cachexia evolves markedly in the end of life and to take advantage of repeated measures, we focused on patients with ≥2 CT images (2--6 images) on record during the year preceding their deaths (n = 368). A selection bias was not apparent in this sample; we showed that the sex distribution, age at death, survival time, primary tumor site, tumor morphology, and body-composition features (ie, muscle and adipose tissues) in patients who had only a single scan were not different from those of the overall cohort at an equal time to death (P \> 0.1). Patients included in the analysis (n = 368) were of advanced stage, and the median time to death of all groups was \<1 y.

Similar study by Tan looking at longitudinal body composition in pancreatic cancer [@tan6973]. 111 patients with metastatic pancreatic cancer: 44 identified with more than one scan. Patients who underwent repeated CT scans were more likely to receive active therapy (71%) and had longer survival than those who had a solitary CT scan (28% receiving active chemotherapy). OVeral median survival 130 days. Age and sarcopenic obesity predicted survival. Sarcopenic obesity had survival of 55 days vs 148 days for those without sarcopenia obesity. Muscle loss was normalized to percent during 100 days. Median interval between scans was ??135 days. Patients grouped in tertiles for muscle gain/loss. Top tertile gained 7% muscle cross-sectional area/100 days, while bottom tertile lost 12% over 100 days. All tertiles lost adipose tissue. **No difference in survival between the tertiles.** \> muscle loss was the prevalent behavior, but 14% of patients with metastatic pancreatic cancer (considered the disease most highly associated with cachexia) exhibited a muscle gain of 7.9 ± 14.4%/100 d).

Lieffers and advanced colorectal cancer: Found liver and spleen increased in size in terminal patients (causing increase in basal metabolic rate). Found more rapid muscle loss with progressive disease [@lieffers1173]. Different thresholds for VAT (-150 to -50) and SAT(-190 to -30). Also estimated muscel surface area using measurements 5cm above L4[@shen2333]. Most rapid change in body composition between 4 months and 1 month prior to death. \>14% of patients gained skeletal muscle during the year preceding death from colorectal cancer (+4.7 ± 5.4%/100 d).

Longitudinal study of patients with advanced non-small cell lung cancer (all with \<1yr survival). [@baracos1133S] \>At referral (median time to death: 265 d), mean body mass index (BMI; in kg/m(2)) was 24.9, with 47.4% of patients being overweight or obese. Only 7.5% overall were underweight as conventionally understood (BMI \< 18.5). Analysis of computed tomography images showed extremely high heterogeneity of muscle mass within all strata of BMI. The overall prevalence of severe muscle depletion (sarcopenia) was 46.8% and was present in patients in all BMI categories.

Caan [@caan1008] examined body composition and survival from colorecal cncer at Kaiser.

### Body composition and gastric cancer

PMID 34774016
