---
title: "Dispairties in GI Cancer"
editor: visual
bibliography: zotero.bib
csl: elsevier-stanford.csl
link-citations: true
---

# Disparities in esophageal cancer

SEER Trends in esophageal cancer: [@corona883] The study included 19,257 EAC cases and 15,162 ESCC cases. EAC mortality increased significantly overall and in non-Hispanic Whites from 1993 to 2012 and from 1993 to 2010, respectively. EAC mortality continued to rise among non-Hispanic Blacks (NHB) (APC = 1.60, p = 0.01). NHB experienced the fastest decline in ESCC mortality (APC = - 4.53, p < 0.001) yet maintained the highest mortality at the end of the study period. Proportions of late stage disease increased overall by 18.5 and 24.5 percentage points for EAC and ESCC respectively; trends varied by race/ethnicity.

SEER no survival difference based upon race [@tramontano2880] T1-3N0M0 adenocarcinoma and squamous cell cancer patients diagnosed between 2003 and 2011. Among 2025 patients, 87.9% were White and 12.1% were Nonwhite. Median survival was 18.7 months for Whites vs 13.8 months for Nonwhites (p = 0.01). In the unadjusted model, Nonwhite patients had higher risk of mortality (HR = 1.29, 95% CI 1.11-1.49, p < 0.0001) when compared to White patients; however, in the Cox regression adjusted model there was no significant difference (HR = 0.94, 95% CI 0.80-1.10, p = 0.44). Surgery, chemotherapy, younger age, lower T stage, and lower Charlson comorbidity score were significant predictors in the full adjusted model. Differences in mortality risk by race/ethnicity appear to be largely explained by additional factors.

NCDB comparison of hospitals [@sridhar1472] NCDB esophageal cancer 2004-2013. Treating facilities were categorized according to their relative burden of uninsured or Medicaid-insured patients. Hospitals with low (LBH), medium (MBH), and high (HBH) safety-net burden were compared with respect to patient demographics, disease and treatment characteristics, and survival. 56,115 patients from 1,215 facilities. HBH treated a greater proportion of racial and ethnic minorities and patients with lower socioeconomic status. Patients at HBH presented at later stages and received primary surgical therapy less often than at MBH and LBH. Survival for patients with esophageal adenocarcinoma did not differ significantly between HBH and LBH after adjusting for age, sex, race, ethnicity, income, comorbidity, stage, histologic type, tumor location, facility type, insurance status, and treatment modality (hazard ratio, 1.06; 95% confidence interval, 0.99 to 1.14; p = 0.093). HBH were associated with a higher mortality risk than LBH for patients with squamous cell carcinoma (hazard ratio, 1.11; 95% confidence interval, 1.02 to 1.20; p = 0.014). There is a mortality risk for patients with squamous cell carcinoma, but not for adenocarcinoma at HBH compared with LBH. Could preferential use of High Burden Hospitals by racial minorities account for their worse outcomes?

Michigan Cancer Registry marital status at the time of diagnosis [@paniaguacruze498] 88.4% of our patients were White and 11.6% were Black. A significantly higher number of White patients were married when compared with Blacks (62.9% v 31.8%, respectively; P < .0001). There was no significant difference in cancer staging between the 2 groups (P = .0671). Married Blacks had similar rates of esophagectomy, chemotherapy, and radiation as married Whites. Both single groups had lower rates of esophagectomy and chemotherapy than married Whites, but single Blacks were the least likely to undergo esophagectomy. Single patients were more likely to refuse treatment.Marital status differs significantly in Black and White patients with esophageal cancer and may help explain racial disparities in cancer care. Further research is needed to explore reasons for care underutilization in single patients and whether these differences translate into clinical outcomes. Marital status at dx is a field in the CR Star data!!

NCDB [@schlottmanndoz045] NCDB Stage I-III esophageal cancer 2004-2015. Multivariable logistic regression models were used to determine the odds of being offered no treatment at all and surgical treatment across race, primary insurance, travel distance, income, and education levels. but was histology included in their model? Multivariable Cox proportional hazards models were used to compare 5-year survival rates across different treatment modalities. A total of 60,621 esophageal cancer patients were included. Black patients, uninsured patients, and patients living in areas with lower levels of education were more likely to be offered no treatment. Similarly, black race, female patients, nonprivately insured patients, and those living in areas with lower median residential income and lower education levels were associated with lower rates of surgery. Patients receiving surgical treatment, compared to both no treatment and definitive chemoradiation, had significant better long-term survival in stage I, II, and III esophageal cancer. Is the negative effect on survival due to race or insurance status/geography?

NCDB stage I-III esophageal cancer 2004-2015 [@savitch581] matched cohorts White:Black. Multi-level modeling was performed to control for random effects of individual hospitals on surgical utilization. 60,041 patients were included (4402 black; 55,639 white). After 1:1 matching, there were 5858 patients. For all stages, significantly fewer black than white patients received surgery. Black race independently conferred lower likelihood of receiving surgery in single-level multivariable analysis (OR (95% CI); stage I, 0.67 (0.48-0.94); stage II, 0.76 (0.60-0.96); stage III, 0.62 (0.50-0.76)) and after controlling for hospital random effects. Hospital-level random effects accounted for one third of the unexplained variance in receipt of surgery. Risk-adjusted 1-, 3-, and 5-year mortality was higher for patients who did not undergo surgery. CONCLUSION: Black patients with esophageal cancer are at higher risk of mortality compared to white patients. This increased risk may be influenced by decreased likelihood of receiving surgical intervention for resectable disease, in part because of between-hospital differences. Improving access to surgical care may improve disparities in esophageal cancer survival. Another way of studying access to surgical care - this time at the facility level. Further support for the theme that access to surgery is barrier to optimal esophageal cancer care. Did this study account for histology? What about SES?

[@swords333] NCDB 2003-2011 Stage I-III esophageal cancer. Median income by zip code and proportion of the zip code residents without a high school diploma were grouped into income and education quartiles, respectively and used as surrogates for SES. Of 11,599 esophagectomy patients who met study criteria, 3,503 (30.2%) were in the highest income quartile, 2,847 (24.5%) were in the highest education quartile, and 610 patients (5%) were black. Before adjustment for SES, black patients had worse overall survival than white patients (median survival 23.0 versus 34.7 months, log rank p < 0.001), and overall, survival times improved with increasing income and education (p < 0.001 for both). After adjustment for putative prognostic factors, *SES was associated with overall survival, whereas race was not.**

[@erhunmwunsee234] NCDB stage I-III 2003-2011. Median income by zip code and proportion of the zip code residents without a high school diploma were grouped into income and education quartiles, respectively and used as surrogates for SES. The association between race and overall survival stratified by SES is explored. Of 11,599 esophagectomy patients who met study criteria, 3,503 (30.2%) were in the highest income quartile, 2,847 (24.5%) were in the highest education quartile, and 610 patients (5%) were black. Before adjustment for SES, black patients had worse overall survival than white patients (median survival 23.0 versus 34.7 months, log rank p < 0.001), and overall, survival times improved with increasing income and education (p < 0.001 for both). After adjustment for putative prognostic factors, SES was associated with overall survival, whereas race was not. Did study include histology in their model?

[@okerekedoab083] NCDB 2004-2017: 127,098 patients. All minority groups were more likely to be diagnosed at advanced stages versus Caucasians after adjusting for covariates (African American OR-1.64 [95% confidence interval 1.53-1.76], Hispanic OR-1.19 [1.08-1.32], Asian OR-1.78 [1.55-2.06]). After adjustment, all minorities were less likely at every stage to receive surgery. Despite these disparities, Hispanics and Asians had improved survival compared with Caucasians. African Americans had worse survival. Racial disparities for receiving surgery were present in both academic and community institutions, and at high-volume and low-volume institutions. Surgery partially mediated the survival difference between African Americans and Caucasians (HR-1.13 [1.10-1.16] and HR-1.04 [1.02-1.07], without and with adjustment of surgery).

California Cancer Registry [@tran3] Esophageal cancer cases 2004-2010. African Americans and Hispanics were more likely to be in the lower SES strata and less likely to receive surgery than Caucasians in this cohort. The proportion of patients receiving chemotherapy and radiotherapy was similar across different racial/ethnic groups. After adjustment for stage, grade, histology, treatments, and SES in multivariate analyses, the mortality risk in African Americans (hazard ratio [HR] 0.96, 95% confidence interval [CI] 0.85-1.07) and Hispanics (HR 0.96, 95% CI 0.89-1.07) did not differ from Caucasians (HR = 1.00, referent), with histology, SES, and surgery largely accounting for unadjusted OS differences. We also observed that African American men had higher adjusted risk of death relative to Caucasian men (HR 1.24, 95% CI 1.07-1.42), but this effect was not observed for African American women compared to Caucasian women (HR 1.12, 95% CI 0.94-1.35). CONCLUSIONS: Race is not an independent risk factor for OS in our population-based analysis of EC cases. Rather, observed differences in OS by race/ethnicity result from differences in cancer histology, SES, surgery, and gender. Sounds like receipt of surgery remains disparate based upon race and accounts for some differences in outcome

## Disparities in access to surgical care

North Carolina [@wong239] compared per capita rate of surgery in 5 high-resource counties with 5 low-resource counties using is data from the Health Cost and Utilization Project State Inpatient Database from 2016. Using the surgical rate observed in the 5 highest-ranked counties (HRCs), the expected surgical rate in the 5 lowest-ranked counties (LRCs) in North Carolina were calculated. Patients 18 years and older who underwent an inpatient general surgery procedure and patients who underwent emergency inpatient cholecystectomy, herniorrhaphy, or bariatric surgery in 2016 were included. The primary outcome was the proportional surgical ratio (PSR), which was the disparity in surgical access defined as the observed number of surgical procedures in the 5 LRCs relative to the expected number of procedures using the 5 HRCs as the standardized reference population. In 2016, approximately 1.9 million adults lived in the 5 HRCs, while approximately 246 854 lived in the 5 LRCs. A total of 28 924 inpatient general surgical procedures were performed, with 4521 being performed in those living in the 5 LRCs and 24 403 in those living in the 5 HRCs. The rate of general surgery in the 5 HRCs was 13.09 procedures per 1000 population. Using the 5 HRCs as the reference, the PSR for the 5 LRCs was 1.40 (95% CI, 1.35-1.44). For emergent/urgent cholecystectomy, the PSR for the 5 LRCs was 2.26 (95% CI, 2.02-2.51), and the PSR for emergent/urgent herniorrhaphy was 1.83 (95% CI, 1.33-2.45). Age-adjusted rate of obesity (body mass index [calculated as weight in kilograms divided by height in meters squared] greater than 30), on average, was 36.6% (SD, 3.4) in the 5 LRCs vs 25.4% (SD, 4.6) in the 5 HRCs (P = .002). The rate of bariatric surgery in the 5 HRCs was 33.07 per 10 000 population with obesity. For the 5 LRCs, the PSR was 0.60 (95% CI, 0.51-0.69). Could we use this same database for esophagectomy? Need to figure out whether patients that have surgery in an read different from where they live are scored as their county of residence or county where surgery was done

[@degajer276]

## Body composition and Racial/Ethnic differences

Age - Sex - Race body composition standard Curves[@magudia319]

Background Although CT-based body composition (BC) metrics may inform disease risk and outcomes, obtaining these metrics has been too resource intensive for large-scale use. Thus, population-wide distributions of BC remain uncertain. Purpose To demonstrate the validity of fully automated, deep learning BC analysis from abdominal CT examinations, to define demographically adjusted BC reference curves, and to illustrate the advantage of use of these curves compared with standard methods, along with their biologic significance in predicting survival. Materials and Methods After external validation and equivalency testing with manual segmentation, a fully automated deep learning BC analysis pipeline was applied to a cross-sectional population cohort that included any outpatient without a cardiovascular disease or cancer who underwent abdominal CT examination at one of three hospitals in 2012. Demographically adjusted population reference curves were generated for each BC area. The z scores derived from these curves were compared with sex-specific thresholds for sarcopenia by using χ2 tests and used to predict 2-year survival in multivariable Cox proportional hazards models that included weight and body mass index (BMI). Results External validation showed excellent correlation (R = 0.99) and equivalency (P < .001) of the fully automated deep learning BC analysis method with manual segmentation. With use of the fully automated BC data from 12 128 outpatients (mean age, 52 years; 6936 [57%] women), age-, race-, and sex-normalized BC reference curves were generated. All BC areas varied significantly with these variables (P < .001 except for subcutaneous fat area vs age [P = .003]). Sex-specific thresholds for sarcopenia demonstrated that age and race bias were not present if z scores derived from the reference curves were used (P < .001). Skeletal muscle area z scores were significantly predictive of 2-year survival (P = .04) in combined models that included BMI. Conclusion Fully automated body composition (BC) metrics vary significantly by age, race, and sex. The z scores derived from reference curves for BC parameters better capture the demographic distribution of BC compared with standard methods and can help predict survival. Investigators at the University of Illinois {@jang557} examined the change in skeletal muscle index during cancer treatment among 212 patients. Among 132 non-Hispanic Black patients, muscle loss during therapy was greater than non-Hispanic White and Other (Asian + Hispanic) (Odds Ratio 3.29 p=0.004). The loss was highest in Black rectal cancer patients (11 units of SMI loss cm2/m2) vs White rectal Cancer (8 cm2/m2). Loss among colon cancer patients was higher in Black patients ( 5.5 cm2/m2) than in White patients (2.5 cm2/m2). Prior to treatment, Blacks had higher SMI than White (similar to findings of Xaio 2019)

Data from Kaiser [@xaio615] examined 3263 patients with non-metastatic colorectal cancer. Black patients had higher lower rates of sarcopenia according to the definition of Prado et al. Patients with higher neutrophil-lymphocyte ratio had higher risk of muscle abnormality. CT scan at L3 was analyed to determine SMI,IMAT,VAT,SAT and TAT (=VAT+SAT+IMAT) using SliceOMatic. Threshold values determined for optimal stratification (cf [@martin153] [@prado639]


Kaiser: Sarcopenia and inflammation in colorectal cancer. [@felicianoe172319]

PMID 24122750

PMID 24866483

Body composition and gastric cancer

PMID 34774016


