---
title: "GI Stromal Tumors"
format: 
  revealjs:
    slide-number: c/t
    width: 1600
    height: 900
    logo: "atriumlogo.jpg"
    footer: "[GI Surgical Oncology Talks](https://gisurgonc.github.io/talks/)"
    #css: ["theme/theme.css"]
    theme: default
      
    echo: false
editor: visual
bibliography: zotero.bib
---

## ACOSOG Z9001

GIST Tumors \>3cm randomized:

-   1 year of imatinib 40mg
-   Observation

Recurrence-free survival 98% vs 83%

No significant difference at 6 years

No difference in overall survival

*Imatinib may simply delay recurrences*

::: aside
Ref
:::

## ACOSOG Z9001

Among patients with tumors ≥10 cm in size: 50% recurred during the first 3 years after randomization

$\Rightarrow$ Some patients may benefit from more extended duration of therapy

Scandinavian Sarcoma Group/Arbeitsgemeinschaft Internistische Onkologie trial XVIII:

Tested longer duration of imatinib therapy for high-risk GIST tumors

(SSG XVIII/AIO) randomized 400 patients with GIST to receive 12 or 36 months of imatinib 400 mg/day after surgical resection of primary tumors

The fact that many recurrences were observed in this trial after completion of adjuvant imatinib (i.e., approximately 50 % of the tumors ≥10 cm in size recurred during the first 3 years after randomization) suggests that some patients may benefit from a longer duration of therapy. Subsequently, the Scandinavian Sarcoma Group/Arbeitsgemeinschaft Internistische Onkologie trial XVIII (SSG XVIII/AIO) randomized 400 patients with GIST to receive 12 or 36 months of imatinib 400 mg/day after surgical resection of primary tumors \[5\]. Patients with a high estimated risk of recurrence according to the modified National Institutes of Health (NIH) criteria (i.e., with at least one of the following characteristics: longest tumor diameter \>10 cm, mitotic count \>10 mitoses per 50 high-power fields (HPF), tumor diameter \>5 cm, and mitotic count \>5 or tumor rupture) were enrolled in the trial. Patients randomized to 36 months of imatinib had significantly longer RFS compared with those randomized to 12 months of therapy (5-year RFS, 65.6 vs. 47.9 %, respectively; HR, 0.46; 95 % CI, 0.32 to 0.65; p \< 0.0001). Those who were treated with 36 months of adjuvant imatinib also had significantly longer OS compared with patients who received 12 months of treatment (5-year OS, 92 vs. 82 %; HR, 0.45; 95 % CI, 0.22 to 0.89; p = 0.02). More discontinuations were noted in the 36-month group for reasons other than GIST recurrence compared with the 12-month group (51 \[25.8 %\] vs. 25 patients \[12.6 %\], respectively). Discontinuation due to adverse events occurred in 13.6 % of patients in the 36-month arm compared with 7.5 % in the 12-month arm.

## SSG SVII

High-risk patients defined:

-   Tumor size \>10cm
-   Mitotic rate \>10/50hpf
-   Tumor size \>5cm with mitotic rate \>5
-   Tumor rupture

High-risk GIST randomized:

-   1 year of imatinib 400mg
-   3 year of imatinib 400mg

5-year Recurrence-free survival 48% vs 66%

5-year Overall Survival 82% vs 92%

::: aside
Ref
:::

## Mutational Testing

Genetic mutations can predict response to imatinib [^1]

[^1]: Meheran JCO 2017

## Positive Margins

::: aside
Gronchi JAMA Surg 2020
:::

## Imatinib 1yr vs 3 yr

::: aside
Joensuu JAMA Oncology 2020
:::

## Wild-Type GIST

-   SDH-Deficient
    -   SDHx mutation
    -   SDH wild-type
    -   Associated with Carney-Stratakis syndrome
-   No SDH Deficiency
    -   NF1-GIST
    -   Sporadic Wild-Type GIST

::: aside
Weldon JCS 2017
:::

## NF1-associated GIST

-   Multicentric (33%)
-   Median age 46
-   Small bowel \>\> Duodenum \>\> Stomach

::: aside
Weldon JCS 2017
:::

## Recurrence Risk

+-------------------+--------------+--------------+
| Risk              | Size         | Mitotic Rate |
+===================+==============+==============+
| Very Low Risk     | \<2cm        | \<5          |
+-------------------+--------------+--------------+
| Low Risk          | 2-5cm        | \<5          |
+-------------------+--------------+--------------+
| Intermediate Risk | \<5cm\       | 6-10\        |
|                   | 5-10cm       | \<5          |
+-------------------+--------------+--------------+
| High Risk         | \>5cm\       | \>5 /50\     |
|                   | \>10cm\      | Any\         |
|                   | Any size     | \>10         |
+-------------------+--------------+--------------+

: Mitotic rate per 50 hpf

::: aside
Fletcher Int J Surg Pathol 10:81 2022
:::

## AFIP Risk Classification

Risk of metastasis based on long-term follow-up of GIST Tumors:

-   1055 gastric
-   629 small intestinal
-   144 duodenal
-   111 rectal

Only tumors \<2 cm with mitotic rate \<5 per 50 HPFs seem to remain consistently free of metastases in follow-up studies; all other categories involve metastatic risk

::: aside
Miettinen Lasota Seminars in Diagnostic Pathology 2006:23:70-83
:::

::: aside
Miettinen Lasota Seminars in Diagnostic Pathology 2006:23:70-83
:::

+-----------+----------------+------------------+----------------+-------------------+---------------+
| **Group** | **Size**       | **Mitotic rate** | **Gastric**    | **Jejunal/Ileum** | **Duodenal**  |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 1         | ≤ 2 cm\*\*     | ≤ 5 per 50 hpf   | None (0%)      | None (0%)         | None (0%)     |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 2         | \>2 ≤ 5 cm     | Very low (1.9%)  | Low (4.3%)     | Low (8.3%)        | Low (8.5%)    |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 3a        | \> 5 ≤ 10 cm   | Low (3.6%)       | Moderate (24%) | High (34%) ǂ      | High† (57%) ǂ |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 3b        | \> 10 cm       | Moderate (12%)   | High (52%)     |                   |               |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 4         | ≤ 2 cm         | Moderate (12%)   | High (52%)     |                   |               |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 5         | \> 2 cm ≤ 5 cm | Moderate (12%)   | High (52%)     |                   |               |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 6a        | \> 5 cm ≤ 10cm | Moderate (12%)   | High (52%)     |                   |               |
+-----------+----------------+------------------+----------------+-------------------+---------------+
| 6b        | \> 10 cm       | Moderate (12%)   | High (52%)     |                   |               |
+-----------+----------------+------------------+----------------+-------------------+---------------+

+----------+-----------------+-----------------+------------+--------------+--------------+
| 4        | ≤ 2 cm          | \> 5 per 50 hpf | None†      | High† (50%)  | §            |
+----------+-----------------+-----------------+------------+--------------+--------------+
| 5        | \> 2 cm ≤ 5 cm  | Moderate (16%)  | High (73%) | High (50%)   | High (52%)   |
+----------+-----------------+-----------------+------------+--------------+--------------+
| 6a       | \> 5 cm ≤ 10 cm | High (55%)      | High (85%) | High (86%) ǂ | High (71%) ǂ |
+----------+-----------------+-----------------+------------+--------------+--------------+
| 6b       | \> 10 cm        | High (86%)      | High (90%) |              |              |
+----------+-----------------+-----------------+------------+--------------+--------------+

# Orientation Manual

{{< qrcode https://gisurgonc.github.io/orientation width=500 height=500 >}}

# References
