---
title: "Body Composition in Rectal Cancer"
editor: visual
bibliography: zotero.bib
csl: elsevier-stanford.csl
link-citations: true
---

# Rectal Cancer Body Composition

NSQIP [@sweigert1004] Morbid obesity was associated with increased risk of any complications after protectomy. BMI was not associated with risk of leak

South Korea 125 patients over 6 years treated with surgery for rectal cancer. Recurrence in 22% associated with visceral to subcutaneous ratio (p=0.045)

Higher BMI associtaed with longer operative time

[@zhang401] significantly longer operative time with obesity and increased LOS

21 [@juvik] higher BMI associated with increased complications

[@lee]

Sarcopenic obesity assot with worse outcome in locally-advancead rectal cancer. Nutrients 15(11) p 2632. Tschann. 96 patients. Anastomotic leak associated with CCI but not body composition. Sarcopenic obesity associated with overal morbidity but not anastomotic leak. Low SMI associated with overall morbidity.

Netherlands [@heus1370] 406 patients over 7 years. VIsceral Obesity defined as visceral fat area \> 100cm2 (272 patient) vs visceral fat area \< 100cm\^2 (134 patients). Visceral obestiy associated with incrase in blood loss, operative timpe, complications, length of stay, but not anastomotic leakage. BMI median of their patients with visceral obesity was 26 (compared with 24 in those without visceral obesity.

Copenhagen [@baastrup177] 102 patients laparoscoy LAR. Visceral fat volume from CT. Visceral obesity defined as to 75th percentile. Among 26 patients with Visceral Fat Volume \> 5.36L, BMI mean was 29.8. No association with margins, readmissio. Increaed LOS

Oxford [@bocca1893] 78 patients surgery for rectal cancer. visceral/subcutaneous fat ratio \>0.4 associated with increased length of stay and complications

USF: [@clark1070] 99 rectal cancer treated with neoadjuvant chemoRT followed by surgery. Visceral/Subcutaneous obesity (\>0.4) or perinephric fat thickness (PNF) associated with co-morbidities and shorter DSF and overall survival.

MSKCC: 586 patients with rectal cancer: obesity (BMI \>30) made no difference in 5 year DFS or OS. [@chern55]

## VIsceral Fat

Cardiovascular disease and visceral fat (review). [@matsuzawa6455]

Visceral fat men with colorectal cancer associated with diabetes, and hypertension. Waist circumference also a predictor [@balentine18]

Pancreaticoduodenctomy MSKCC: 356 Whipple - primary risk factors for complications were absence of pancreatic atrophy and central obesity as measured by retrorenal visceral fat (\>2cm)

Netherlands [@berkel376] 99 patients over 5 years. Sarcopenic obesity defined as BMI \>25 and SMI below median: Associated with overall complications. Low muscle density associated with overall and Grade 3-5 complications

Rush University 47 patients Sarcopenia present in 50% of patient and associated with postoperative complications and blood transfusions [@jochum1372]

## Skeletal muscle loss during neoadjuvant therapy

Associated with mortailty

Yonesi South Kored [@chung820] 93 patients underdoing neoadjuvant therapy 23 had severe muscle loss. Risk factors for survival were age, ypT Stage, severe muscle loss, and sarcopenia after neoadjuvant therapy. T4 disease associated with severe muscle loss.

OSaka: Change in psoas muscle index \>10% associated with poor prognosis [@fukuoka5157] and complications

Australia [@yassaie1146]. 92 patients mean loss of psoas muscle was 5%. Patients with residual tumor after chemoRT had less change in psoas area. greater loss of muscle in those with leak (10% vs 4%) and those who developped metastatic disease (10% vs 4%)

Peking \[\@\]
