---
title: "Sarcopenia AI Methods"
editor: visual
bibliography: zotero.bib
csl: elsevier-stanford.csl
link-citations: true
---

## Machine Learning for CT analysis

Fully automated tools 94-96 [@graffy20190327] [@burns311] [@hemke387]

Machine learning [@lee487] [@popuri512]

L3 slice selection [@islame363]

# Image Libraries

Bilic P, Christ PF, Vorontsov E, Chlebus G, Wu J. The liver tumor segmentation benchmark (lits). arXiv:1901.04056 (2019).

[Google Scholar](http://scholar.google.com/scholar_lookup?author=P+Bilic&author=PF+Christ&author=E+Vorontsov&author=G+Chlebus&author=J+Wu+&publication_year=2019&title=The+liver+tumor+segmentation+benchmark+(lits))

40\. Heller N, Sathianathen N, Kalapara A, Walczak E, Moore K, Kaluzniak H, et al. The kits19 challenge data: 300 kidney tumor cases with clinical context, ct semantic segmentations, and surgical outcomes. *arXiv e-prints.* (2019).

[Google Scholar](http://scholar.google.com/scholar_lookup?author=N+Heller&author=N+Sathianathen&author=A+Kalapara&author=E+Walczak&author=K+Moore&author=H+Kaluzniak+&publication_year=2019&title=The+kits19+challenge+data%3A+300+kidney+tumor+cases+with+clinical+context,+ct+semantic+segmentations,+and+surgical+outcomes&journal=arXiv+e-prints)

Liver segmentation using GAN [@he794969]

### Voroni = ABACAS

Investigators with financial relatinoships with Voronoi: Mirza Beg, Karteek Popuri, Vincent Chow

Chung H, Cobzas D, Birdsell L, Lieffers J, Baracos V. Automated segmentation of muscle and adipose tissue on CT images for human body composition analysis. in SPIE Medical Imaging. 2009. International Society for Optics and Photonics.[@chung]

Popuri K, Cobzas D, Esfandiari N, Baracos V, Jagersand M. Body composition assessment in axial CT images using FEM-based automatic segmentation of skeletal muscle. IEEE Trans Med Imaging. 2016; 35:512--20. [@popuri512]

Voronoi comparison of L3 vs T12-L5 volumes. Agreement in measurements with Bland-Altman method. Unusuable scans in 125 patients (metal implant, muscle cut off, bright truncation, major segmentation error) out of 2996 AND 159 images with abnormalities which could change outcomes (pannus, armd in view, minor truncation). Dice coeficcients for SMI was 0.97, 0.99 for SAT, 0.96 for VAT.To quantify the agreement between the single-slice and multi-slice measurements, we used the Bland–Altman method. The bias (mean of the differences) and standard error, as well as the upper and lower limits of agreement (LOA: bias ± 1.96 \* SD) were calculated.17 Individual measurements were classified as outliers if they fell outside the LOA for the respective tissue type. Cohen's kappa coefficients were estimated to assess the agreement between the single-slice area and multi-slice volume categories described above (three-level, SD-based variable), as well as equivalent categories based on SKM radiodensity. Aligning with Cohen's definition,18 Cohen's kappa coefficients were interpreted as follows: 0.01–0.20 as no correlation, 0.21–0.39 as minimal, 0.40–0.59 as weak, 0.60–0.79 as moderate, 0.80–0.90 as strong and above 0.90 as near-perfect correlation. Body composition from single versus multi-slice abdominal computed tomography: Concordance and associations with colorectal cancer survival[@anyene2974]

Giavarina D. Understanding Bland Altman analysis. Biochem Med (Zagreb) 2015;25:141–151.

McHugh ML. Interrater reliability: the kappa statistic. Biochem Med (Zagreb) 2012;22:276–282.

### AutoMATiCA

Paris Automated Muscle and Adipose Tissue Composition Analysis (AutoMATiCA) is a Python-based software that uses a neural network to automatically segment an L3-level axial CT image into the following discrete tissue types: skeletal muscle, intermuscular adipose tissue, visceral adipose tissue, and subcutaneous adipose tissue, calculating both cross sectional area and density via Hounsfield units. Scans can be systematically analyzed in under a minute, greatly increasing throughput and inter-rater reliability through reliance on a single algorithm. AutoMATiCA has been shown to correlate well with manually-assessed body composition quantifications; Automated body composition analysis of clinically acquired computed tomography scans using neural networks
