---
title: "To Do"
editor: visual
bibliography: zotero.bib
---

## Effect of age on additional benefit of surgery after ChemoRT

\
NCDB [@jensendoac050] compared survival with chemoradiation+Surgery vs chemoradiation alone and found a survival benefit to surgery, except for patients over age 80 with adenocarcinoma and patients with squamous cell carcinoma with Charson/Deyo 2 or 3+, in whom there was no survival advantage or detriment to surgery\
\
NCDB [@farrow996] Compared survival of stage II or III esophageal cancer in 17,495 patients, of whom 11,680 underwent esophagectomy and 5815 received chemoradiation. Survival after esophagectomy worsened with increasing age and decreased considerably after age 73. More use of dCRT after age 73. Survival benefit of surgery over chemoradiation in all ages, including octogenarians.\
\
SEER [@lv8483] 1596 Elderly patients with esophageal cancer: 278 had surgery.  Longer survival with trimodality therapy.\
\
he perioperative period is when patients are at most risk of developing cardiopulmonary complications with an operative mortality rate of 13.4% in those who are between 70--79 years old and 19.9% in those over the age of 80 (7,8).

Operative moratality after esophagectomy in those over age 80 is 19.9% (vs 8.8% under age 90) from National Inpatient Sample data [@finlayson729]

# Frailty and outcomes after esophagectomy

Jack et al [@jack1313a] studies VO2max before and after neoadjuvant chemoradiation prior to esophagectomy. Patients with lower baseline VO2max prior to surgery had lower 1-year survival after esophagectomy

\# Retrospective Trimodality vs dCRT\
Italy [@castoro1375] Squamous cell 77 patients over 16 years. Comparable survival with dCRT vs Trimodality even after correcting for propensity score\
\
Dutch[@faiz986] Factors accounting for choice of dCRT vs Trimodality: age \>75, hypertension+diabetes, CV+pulmonary. Adenocarcinoma: better survival with Trimodality. SCCA: Age \>75 or \>2 comorbidities overall survival was comparable between groups.\
\
Taiwan [@wang255] 5832 patients with SCC: Trimodality in 1754 and dCRT in 4078. Survival at 3 years 41% with trimodality vs 17% with dCRT\
\
MDACC [@zhou1207] Squamous cell: 143 Trimodality-eligible patients: 60 had trimodality therapy and 83 had chemoRT. Longer survival in trimodality group (77 vs 33 months). For those with a complete clinical response, trimodality resulted in 123 moths survival vs 55 months with dCRT. Trimodality therapy was not associated with longer overall survival but predicted recurrence-free survival.\
\
UK [@hategan612] 102 patients with esophageal cancer: 55 trimodality and 47 dCRT. Longer survival with trimodality\
\
\# ChemoRT in Trimodality-eligible patients\
\
MDACC [@taketa300] 662 patient eligible for trimodality therapy received chemoradiation. 61 patients (9.8%) refused surgery.  5-year overall survival 58% and relapse-free survival 35%. 13 patients developed localized recurrences, of whom 12 underwent salvage esophagectomy.\
\
MDCAA [@taketa95]\
\
\# Active Surveillance\
Dutch preSano [@noordman965]\
\
SANO randomized trial [@noordman142]\
\
Editorial [@vanderwilk462]\
\
\# Randomized trials of Trimodality vs dCRT\
FFCD 9012 [@bedenne1160]\
German Trial [@stahl2310]\
\
\# Reviews - Trimodality vs dCRT\
\
[@vellayappanCD010511] Addition of surgery to dCRT adds little or benefit for patients with squamous cell carcinoma. Authors could not determine whether there was benefit of the addition of surgery for adenocarcinoma and GE junction cancers.\
\
[@voeten1271] No clear advantage of trimodality therapy over dCRT\
\
\
\# Lenchik Papers\
IV Contrast\
\
Tube current - [@fuchs2455]\
Slice Thickness [@morsbach50]\
Contrasst challenges [@bae32]\
Muscle L4 contrast [@boutin1046]\
IV contrast and muscle size [@vanderwerf366] [@vanvugt1707]\
kV[@morsbach9]\
\
ICC 24/35/42\
[@fuch2455]\
[@vanderwerf366]\
[@barnard1686]\
[@perthen142]\
\
Machine learning 43-46\
[@jang360]\
ML methods from Lung Cancer Screening Trial. CNN with U-NET. Left paraspinous muscle at T12. CSA and MA.  Dice scores of 0.94 r\^2 0.86 for CSA and 0.2 for MA. Manual segmentation with Mimics.\
In the input pipeline, the ground truth image was extracted from the Mimics-exportedDigital Imaging and Communications in Medicine (DICOM) using a simple R \[69\] procedure, with the oro.nifti \[70\] library providing input and output functionality. The mask was cleaned using a custom Python script built with NiBabel \[71\] for I/O, SciPy \[72\] for spatial calculations, and NumPy \[73\] for general numeric operations. Additional preparation of ground truth data used the ImageMath and fslstats programs of the Advanced Normalization Tools \[74\] and FMRIB Software Library \[75\] respectively.\
Preparation of the 3-channel input images used scikit-image's \[76\] rescale_intensity and equalize_adapthist functions for clipping and equalization. Overlap measures were implemented as functions of the confusion matrix provided by scikit-learn's \[77\] confusion_matrix function and assembled into easily-analyzed tabular representations using Pandas \[78\]. Subsequent correlation analyses of the muscle CSA and MA were performed with R's cor.test function. Algorithm can't select L3 \[Working with DICOM and IIfTI in R\](<http://www.jstatsoft.org/v44/i06/>.) Snakemake[@koster2520]\
\
NLST and mortality [@lenchik1] Increased SMA and SMD associated with longer survival\
\
[@barnard1686]\
[@lenchik1695]\*\*\*\
[@kullberg10425]\
\
Sarcopenia methods - varies 19/92\
[@amini1671]\
Review of challenges in methods inconsistency\
[@hopkins1381]\
\
myosteatosis adds value 93\
[@martin227]\
\
Fully automated tools 94-96\
[@graffy20190327]\
[@burns]\
[@hemke387]\
\
Machine learning\
[@lee487]\
[@popuri512]\
\
\
\
L3 slice selection\
[@islame363]\
\

\
