---
title: "Statistics"
editor: visual
bibliography: zotero.bib
---

# R packages

Therneau T. A package for survival analysis in R. R package version 3.3--1. 2022. https://CRAN.R-project.org/package=survival

edersen TL. patchwork: the composer of plots. R package version 1.1.1. 2020. https://CRAN.R-project.org/package=patchwork. 2020.

Zhu H, Travison T, Tsai T, Beasley W, Xie Y, Yu G, et al. kableExtra: construct complex table with 'kable' and pipe syntax. R package 1.3.4. 2021. https://CRAN.R-project.org/package=kableExtra

Sjoberg DD, Whiting K, Curry M, Lavery JA, Larmarange J. Reproducible summary tables with the gtsummary package. R J 2021;13:570--580.

# Length of Stay

Because length of stay has a naturally skewed distribution, we used GLM with a negative binomial distribution appropriate for skewed distribution. Austin P

\# Modeling age as a variable

Cubic splines with age for surgical risk model \[\@passos316\]

Cubic splines with age for risk model of cardiac surgery \[\@lee973\]

Box-Tidwell test Box GEP, Tidwell PW. Transformation of independent variables. Technometrics 1962; 4: 531-- 50

Can also test for assumption of linearity by creating deciles (or other ordered categories)

Age and BMI converted to ordinal variables to avoid assumption of linearity \[\@fong1020\]

Age trichotomized because it violated the assumption of linearity \[\@willingham214\]
