---
title: "To Do"
editor: visual
---
## This week

**Clinic**
Make up new folders
Need common calendar

Track down Limentani referral


**R Tools**
GT
FormatTable
Formatter
DescTools:PercTable
gmodels:CrossTable


Python Books
Crash Course
Python Distilled (reference)
Impractical python projects

**Send Cindy information about size limits for FedEx**

Review indeterminate CT scan

?Is there a way to programmatically review CT (single slice) images??

Look for variances between K/M and Maddie


##LOI

Get data to Erin for chemoRT vs chemoRT+S - survival at 1 year and 3 years stratfied by body composition and age (SMG)


Body Composition - Find CT scans at 1 year post-op after esophagectomy

What is known about body composition changes 1 year after bariatric surgery?

Make sure that race variable for Wake RadOnc is compatible with REDCap

**How to update existing REDCap records with a new variable?**

Flag variable for scans that need to be re-read

Design REDCap for easy extraction of data (for Anesthesia AND Body Composition )

Need variables in REDCap which will allow for cohort selection

CPA citizenship

Re-scheduled esophagectomy - PInkcney -  Can Tom Pacicco's patiet go into his slot??

Get Cogito study materials from Lance Ritchie

**Transfer funds to Grace**

SOLD
  Clean up cM and cN 
    Clarify NULL (MySQL) vs NA (R) vs "" (?REDCap export via CSV)
  Compare T and N definitions between AJCC 6/7/8 (and create table)
  
Drop Lenchik's CTSI application into folder

Set up meeting with Hart (prior to meeting with Brent Matthews)

Set up meetings with residents

  Jordan - get Race data input first AND request addresses from Mike Inman
  XX - Esophagectomy outcomes and body composition
    Baseline value at diagnosis
    Values at restaging immediately preop (would allow for comparision with surgery only)
    
Need to decide how long to wait to get Wake Forest data - One publication or two?  Need to look at abstract deadlines


Body composition as a predictor of periop mortality 2012+ from CMC (use immediate measurement)
  Combine with AGE and 5-factor frailty score (NSQIP) 
    CHF, HTN, Diabetes, Functional status,  **Need to get Katelyn/Matigan working on this**
    
    **IS THERE A WAY TO PULL Dx CODING FROM DATA WAREHOUSE??**
      Two stage - pull all encounters in prior 2 years
        If too many - sample inpatient encounters
        Max of 1000 records 
        Can Rupali help with this???
        
        

Body composition as a predictor of survival for locally-advanced esophageal cancer (in conjunction with pathologic staging).



Change in body composition as a predictor of survival

Body composition to stratify ChemoRT vs ChemoRT+Surgery

Body composition vs CGA
    
How can we get UMPI from Data Warehouse? - in short-term, manually pull from Cerner

Need FU letter on letterhead for survivors

Stage IV colorectal patients getting immunotherapy alone - look at body composition vs toxicity

Need imaging machine learning project
  
  
Research auto-enoder
  


  - Other topics to discuss with Richard
    - Re-funding Matigan and Katelyn
    - Paying for manuscripts
- Student research projects
- RSVP for alumni weekend:
  - Friday 6pm legion brewery
  - Saturday 8-11:30am CME symposium
  - Saturday 6:30 dinner at Mimosa

- email Declan Walsh about prehabilitation
- Set up blood management program meeting
- Meet with Meredith about J tubes EnFit
- Prep meeting with Armie Perla-Metz
- 20 year appreciation gift -order








### Body composition and esophageal cancer

- Email Sachdev about research
- Email Kevin about research resident
- Plan REDCap
  - Prepare prototype REDCap
    - Add options to existing fields (eg Race)
    - Correct fields:
      - Atrium facilities
      - Race
      - Re-staging PET and CT information
      - Add restaging CT scan (in addition to PET)
      - Add multi-check box for restaging scans
  - Mappings from NCDB (look at ACS FORDS dictionary)
  - Need mapping from STS Database
  - Need mapping from NSQIP ()
  - Need mapping to consortium complications
  - Add data definitions to REDCap data dictionary

#### Dialog with SurgOnc and RadOnc at Wake

- What data is available (for what time periods)?
- Harmonize data definitions
- Can we leverage other existing data sources?
  - NSQIP (COPD, CHF, HTN, Diabetes)
  - Cancer registry (case-finding, staging, recurrence status, vital staus)
  - Data warehouse (Race, Ethnicity, Vital Status, postop length of stay )
  
### T1 esophageal cancer

Look at whether SES or Race plays a role in failure to followup after EMR for early stage esophageal cancer

## Clinic

- Counselling form Add orders   
- Annetta - shared calendar   
- Connect with Shelby via LinkedIn



- Make missing data reports  
- email Hart and Josh about pilot     
- Memorial service music

**Ignition and Pilot Grants**

Scholarly activity to Shelly
Sign up for interviews
Cogito 170 certification

# Home

- Get Daniel 30th on calendar
- Submit receipts for CMDA trip to Indianapolis
- Plan ahead for book purchases by end of year
- FU with Jen and Mario
- Dinner with Terry and Heidi - think about dates
- Plan for DEIP - NOvember 11th
- Plan for White Christmas party Friday December 2nd



- Watch Sermon from 10/3 and 10/10
- Connect with Caleb and plan ?trip out

# Random

- Summer students 2023: Prepare practice dataset with RStudio
- Review old cases and send followup letters
